### ISSUE TITLE
Cannot import `__importlib_util` while running `pytest`

### ISSUE THREAD

**Issue by pbzweihander** [RustPython/RustPython#1264]
```
$ pytest -v -k test_cpython_whats_left_modules
============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /some/path/to/python3.7
cachedir: .pytest_cache
rootdir: /some/path/to/rustpython/tests
collecting ... collected 324 items / 323 deselected / 1 selected

test_snippets.py::SampleTestCase::test_cpython_whats_left_modules FAILED [100%]

=================================== FAILURES ===================================
________________ SampleTestCase.test_cpython_whats_left_modules ________________

self = <test_snippets.SampleTestCase testMethod=test_cpython_whats_left_modules>

    def test_function(self):
>       perform_test(filename, method, test_type)

test_snippets.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_snippets.py:40: in perform_test
    run_via_cpython(filename)
test_snippets.py:50: in run_via_cpython
    subprocess.check_call([sys.executable, filename], env=env)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/some/path/to/python3.7', '/some/path/to/rustpython/tests/snippets/whats_left_modules.py'],)
kwargs = {'env': {<env omitted>, ...}}
retcode = 1
cmd = ['/some/path/to/python3.7', '/some/path/to/rustpython/tests/snippets/whats_left_modules.py']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/some/path/to/python3.7', '/some/path/to/rustpython/tests/snippets/whats_left_modules.py']' returned non-zero exit status 1.

/some/path/to/python3.7/subprocess.py:347: CalledProcessError
---------------------------- Captured stderr setup -----------------------------
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
    Finished release [optimized] target(s) in 0.12s
----------------------------- Captured stderr call -----------------------------
/some/path/to/rustpython/tests/snippets/whats_left_modules.py:30: DeprecationWarning: the formatter module is deprecated
  if mod not in ("this", "antigravity")
Traceback (most recent call last):
  File "/some/path/to/rustpython/tests/snippets/whats_left_modules.py", line 33, in <module>
    rustpymods
  File "/some/path/to/rustpython/tests/snippets/whats_left_modules.py", line 30, in <lambda>
    if mod not in ("this", "antigravity")
ModuleNotFoundError: No module named '__importlib_util'
=============================== warnings summary ===============================
snippets/test_warnings.py:3
  /some/path/to/rustpython/tests/snippets/test_warnings.py:3: UserWarning: Test
    _warnings.warn("Test")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============= 1 failed, 323 deselected, 1 warnings in 0.61 seconds =============

```

While running `test_cpython_whats_left_modules` test case, my cpython fails to import `__importlib_util`.

I'm using Arch Linux with Python 3.7.4. I don't think this is RustPython's bug, but it's little annoying that not all test cases pass.

**Comment by coolreader18** [comment]
Interesting. Have you set your `PYTHONPATH` or `RUSTPYTHONPATH` environment variable to the RustPython `Lib` directory? And did you make sure that your python environment was clean when you ran `whats_left.sh` or `tests/not_impl_gen.py`? And, can you see if `__importlib_util` is in the generated file `tests/snippets/whats_left_modules.py`?

**Comment by pbzweihander** [comment]
My environment variables were clean:

```
$ env | rg PYTHON

$ 
```

Running `pytest` with `RUSTPYTHONPATH` variable also fails.

- `RUSTPYTHONPATH=Lib pytest` fails
- `RUSTPYTHONPATH=../Lib pytest` fails
- `RUSTPYTHINPATH=/absolute/path/to/rustpython/Lib pytest` fails, too.

When I set `PYTHONPATH` to `Lib`, it fails too:

```
$ PYTHONPATH=Lib python tests/snippets/whats_left_modules.py
Fatal Python error: init_sys_streams: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007f24ffff9740 (most recent call first):
zsh: abort (core dumped)  PYTHONPATH=Lib python tests/snippets/whats_left_modules.py

$ PYTHONPATH=Lib python -c "import __importlib_util"              15:53:27
Fatal Python error: init_sys_streams: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007f16688d0740 (most recent call first):
zsh: abort (core dumped)  PYTHONPATH=Lib python -c "import __importlib_util"

```

**Comment by coolreader18** [comment]
Ah, I'm having the same issue. I'll look into it on my machine then.

**Comment by coolreader18** [comment]
Ah, it's that it's specifically importing the absolute path of the RustPython module. I can just push a quick fix to master to try/except the `__importlib_util` module and otherwise `import importlib.util as __importlib_util`.

**Comment by coolreader18** [comment]
Hmm, nevermind. It looks like it just doesn't like there being a module that is in RustPython's Lib dir and not CPython's, as it tries to import every single module that is in `RustPython/Lib` by name rather than path. I believe @youknowone is working on importlib now, though, so this should be a short-lived problem and we should be able to get rid of the `__importlib_util` hack.

**Comment by coolreader18** [comment]
Ok, should be fixed now. Try rerunning `whats_left.sh` and then `pytest` .
