### ISSUE TITLE
Infinite recursion cause segfault, not RecursionError

### ISSUE THREAD

**Issue by xarus01** [RustPython/RustPython#1374]
## Code

```
def a():
    a()
a()
```

## Expected
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in a
  File "<stdin>", line 2, in a
  File "<stdin>", line 2, in a
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

## Result
```
[1]    36945 segmentation fault  RUSTPYTHONPATH=Lib cargo run
```

**Comment by youknowone** [comment]
The given example now raises `RecursionError` (though the message is not compact as CPython)
