### ISSUE TITLE
Wrong error message when calling a non-callable object

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1416]
CPython

```
>>> 'linux'()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object is not callable
>>> 1()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
```

RustPython

```
>>>>> 'linux'()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unsupported method: __call__
>>>>> 1()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unsupported method: __call__
```

**Comment by pitachips** [comment]
Can I fix the message?

**Comment by dralley** [comment]
Sure!
