### ISSUE TITLE
UnboundLocalError is not returned

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1454]
```
x = 10
def foo():
    x += 1
    print(x)
foo()
```

### Expected

```
Traceback (most recent call last):
  File "test3.py", line 5, in <module>
    foo()
  File "test3.py", line 3, in foo
    x += 1
UnboundLocalError: local variable 'x' referenced before assignment
```

### Actual

```
11
```

This might be related to #1333

**Comment by sanxiyn** [comment]
In fact, there is no UnboundLocalError defined at all.

**Comment by Lynskylate** [comment]
In fact this is because the generated bytecode is wrong.
```python
def foo():
    x += 1

dis(foo)
# RustPython bytecode
""""
                 0 LoadName             (x, Free)
                 1 LoadConst            (1)
                 2 BinaryOperation      (Add, true)
                 3 StoreName            (x, Free)
""""
# Python bytecode
"""
            0 LOAD_FAST                0 (x)
              2 LOAD_CONST               1 (1)
              4 INPLACE_ADD
              6 STORE_FAST               0 (x)

"""
```
RusyPython bytecode Load x from free scope,  it means that  load variables globally when reading from a local scope fails.
In cpython, it just load variable from locals.
```c
//ceval.c 1329
        case TARGET(LOAD_FAST): {
            PyObject *value = GETLOCAL(oparg);
            if (value == NULL) {
                format_exc_check_arg(tstate, PyExc_UnboundLocalError,
                                     UNBOUNDLOCAL_ERROR_MSG,
                                     PyTuple_GetItem(co->co_varnames, oparg));
                goto error;
            }
```

**Comment by dralley** [comment]
This seems to be fixed now
