### ISSUE TITLE
The sys module does not have stderr in frozen

### ISSUE THREAD

**Issue by rls1004** [RustPython/RustPython#1566]
## Feature
```
>>>>> import sys
>>>>> sys.stderr
<TextIOWrapper object at 0x55e8c8167ea0>
```
```
$ ./target/debug/rustpython -v
Traceback (most recent call last):
  File "_frozen_importlib", line 1162, in _install
  File "_frozen_importlib", line 1154, in _setup
  File "_frozen_importlib", line 1122, in _builtin_from_name
  File "_frozen_importlib", line 686, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 227, in _verbose_message
AttributeError: module 'sys' has no attribute 'stderr'
```

Although `sys.stderr` is implemented, the `stderr` attribute does not exist in the `sys` module when the `_verbose_message()` function is called.

The problem seems to be caused by `sys.stderr` being implemented in `_sitebuiltins.py` rather than `sysmodule.rs`.

**Comment by dralley** [comment]
This is no longer true, it can be closed @youknowone 

```
[dalley@localhost RustPython]$ ./target/debug/rustpython -v
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
....
....
(lots of output)
```
