### ISSUE TITLE
Unsupported format string for bytes

### ISSUE THREAD

**Issue by rls1004** [RustPython/RustPython#1569]
### expected result
```
>>> b'Hello %b!' % b'World'
b'Hello World!'
```

### actual result
```
>>>>> b'Hello %b!' % b'World'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unsupported operand types for '%': 'bytes' and 'bytes'
```

Format string does not work for bytes.

## Python Documentation

PEP 461 - percent formatting support for bytes and bytearray
https://docs.python.org/3/whatsnew/3.5.html#pep-461-percent-formatting-support-for-bytes-and-bytearray

**Comment by yanganto** [comment]
issue update:
- support percent formatting for byte
- percent formatting for bytearray is not ready

```
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> bytearray('hello%b', 'utf-8') % b' world'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unsupported operand types for '%': 'bytes' and 'bytearray'
>>>>> b'Hello %b!' % b'World'
b'Hello World!'
```

**Comment by youknowone** [comment]
both done by @yanganto 🎉
