### ISSUE TITLE
sys.getdefaultencoding() ;sys.stdout.encoding Not Implement

### ISSUE THREAD

**Issue by QGB** [RustPython/RustPython#1583]
#1514 

## Feature
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_frozen_importlib", line 1113, in __import__
  File "_frozen_importlib", line 1050, in _handle_fromlist
  File "_frozen_importlib", line 1042, in _handle_fromlist
  File "_frozen_importlib", line 1014, in _gcd_import
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 975, in _find_and_load_unlocked
  File "_frozen_importlib", line 686, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 677, in _load_unlocked
  File "_frozen_importlib", line 671, in _load_unlocked
  File "_frozen_importlib_external", line 788, in exec_module
  File "/home/qgb/qgb/U.py", line 9, in <module>
    gsdecode=decoding='utf-8';gsencode=gsencoding=encoding=stdout.encoding
AttributeError: 'TextIOWrapper' object has no attribute 'encoding'
```
## Python Documentation
https://docs.python.org/3/library/sys.html#sys.getdefaultencoding

**Comment by youknowone** [comment]
`TextIOWrapper` now has encoding. please post reproducible code if the problem is not solved.
