### ISSUE TITLE
Issues with set iterators

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#1652]
### Expected

```
>>> t = (1, 2, 3)
>>> l = [1, 2, 3]
>>> s = {1, 2, 3}
>>> d = {'a': 1, 'b': 2, 'c': 3}
>>> iter(t)
<tuple_iterator object at 0x7f8e1eedd0d0>
>>> iter(l)
<list_iterator object at 0x7f8e1edcecd0>
>>> iter(s)
<set_iterator object at 0x7f8e1edcf410>
>>> iter(d)
<dict_keyiterator object at 0x7f8e1ef4ce90>
>>> reversed(iter(l))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list_iterator' object is not reversible
>>> i = iter(s)
>>> next(i)
1
>>> s.remove(2)
>>> next(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Set changed size during iteration
>>> i = iter(d)
>>> next(i)
'a'
>>> del d['b']
>>> next(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: dictionary changed size during iteration
```

### Actual

```
>>>>> t = (1, 2, 3)
>>>>> l = [1, 2, 3]
>>>>> s = {1, 2, 3}
>>>>> s = {'a': 1, 'b': 2, 'c': 3}
>>>>> iter(s)
<list_iterator object at 0x55853bcaf510>       # <--- should be "set_iterator" object
>>>>> iter(t)
<tuple_iterator object at 0x55853bcaf510>
>>>>> iter(l)
<list_iterator object at 0x55853b881e10>
>>>>> iter(d)
<dict_keyiterator object at 0x56425a1aa9b0>
>>>>> reversed(iter(l))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument to reversed() must be a sequence    # <--- error can be improved
>>>>> s = {1, 2, 3}
>>>>> i = iter(s)
>>>>> next(i)
1
>>>>> s.remove(2)
>>>>> next(i)
2                               # <--- Should have returned RuntimeError
>>>>> i = iter(d)
>>>>> next(i)
'a'
>>>>> del d['b']
>>>>> next(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: dictionary changed size during iteration
```

**Comment by dralley** [comment]
I'll work on this

**Comment by dralley** [comment]
This kind of fell by the wayside and I'm not sure if I'll have time to finish it any time soon

**Comment by coolreader18** [comment]
No problem, I'm sure somebody else will pick it up.

**Comment by hatee-hatee-hatee-ho** [comment]
I'd like to work on this issue.

**Comment by dralley** [comment]
I think this can be closed now
