### ISSUE TITLE
main thread panic: ModuleNotFoundError: No module named 'io'

### ISSUE THREAD

**Issue by doyshinda** [RustPython/RustPython#1796]
## Problem
Not sure if this is a problem with my setup, but I get the following when I try to run RustPython (full stacktrace below):
```
$ RUST_BACKTRACE=1 cargo run
...
ModuleNotFoundError: No module named 'io'
thread 'main' panicked at 'initializiation failed; exception backtrace above', vm/src/vm.rs:537:9
```

Running `git bisect`, this starts happening on commit `db65c8d512eca633a3b5ff67fb76c178eadffdff`.

## My setup:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```
Tried with both rustc `1.40.0` and `1.41.1`. Let me know if there is any more info needed to help debug this.

## Full stack trace
```
ModuleNotFoundError: No module named 'io'
thread 'main' panicked at 'initializiation failed; exception backtrace above', vm/src/vm.rs:537:9
stack backtrace:
   0:     0x55ff27bae544 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55ff27bae544 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55ff27bae544 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55ff27bae544 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55ff27bd2dcc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55ff27baa5f7 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55ff27bb09ce - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55ff27bb09ce - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55ff27bb09ce - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55ff27bb06c1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55ff27bb106b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55ff27bb0c0e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55ff27bb0b4f - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x55ff265cf0b4 - rustpython_vm::vm::VirtualMachine::_py_panic_failed::hfc47b306ca276d1b
                               at vm/src/vm.rs:537
  14:     0x55ff26b629aa - rustpython_vm::vm::VirtualMachine::expect_pyresult::{{closure}}::hade127cdb15772c6
                               at vm/src/vm.rs:545
  15:     0x55ff26de6129 - core::result::Result<T,E>::unwrap_or_else::h18aa85333457113d
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:818
  16:     0x55ff26b62968 - rustpython_vm::vm::VirtualMachine::expect_pyresult::h50dee9e62f34d0f0
                               at vm/src/vm.rs:545
  17:     0x55ff265cba83 - rustpython_vm::vm::VirtualMachine::initialize::h4cee75a22f9e331d
                               at vm/src/vm.rs:268
  18:     0x55ff265cb03e - rustpython_vm::vm::VirtualMachine::new::h0bf4eb366bbd4b73
                               at vm/src/vm.rs:217
  19:     0x55ff265b0553 - rustpython::main::h59884244325e27db
                               at src/main.rs:39
  20:     0x55ff26593910 - std::rt::lang_start::{{closure}}::h338265f116359936
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  21:     0x55ff27bb0a93 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  22:     0x55ff27bb0a93 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  23:     0x55ff27bb578a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  24:     0x55ff27bb154d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  25:     0x55ff27bb154d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  26:     0x55ff27bb154d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  27:     0x55ff265938e9 - std::rt::lang_start::he5522e7fdad1b32d
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  28:     0x55ff265b797a - main
  29:     0x7f9626360b97 - __libc_start_main
  30:     0x55ff2658593a - _start
  31:                0x0 - <unknown>
```

**Comment by coolreader18** [comment]
Have you set your RUSTPYTHONPATH environment variable to the `Lib` directory in your rustpython checkout?

**Comment by doyshinda** [comment]
Nope, I sure didn't, setting that fixes it. Apologies for the noise!

**Comment by coolreader18** [comment]
Oh, no problem. Up until that commit we didn't depend on any python standard library modules in the startup process, and now we do. The frequent contributors to RustPython all have the RUSTPYTHONPATH env variable set in their shell config, so we don't often think about the onboarding process for new contributors; I think the vm initialization definitely needs some improvement w.r.t. inferring where the Lib directory is.

**Comment by doyshinda** [comment]
No worries, I contributed a few commits a few months ago and didn't recall having to set `RUSTPYTHONPATH`, makes sense why now. Thanks for the explanation!
