### ISSUE TITLE
README first examples are broken

### ISSUE THREAD

**Issue by alanjds** [RustPython/RustPython#1829]
At least the two first examples of README are broken:
```console
$ git clone https://github.com/RustPython/RustPython
$ cd RustPython
$ cargo run demo.py
Hello, RustPython!
```
```console
$ cargo run
Welcome to rustpython
>>>>> 2+2
4
```

Right now (MAR/2020) they break trying to import io:
```console
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/rustpython`
thread 'main' panicked at 'initializiation failed; run with RUST_BACKTRACE=1 to see Python backtrace', vm/src/vm.rs:537:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```console
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rustpython`
ModuleNotFoundError: No module named 'io'
thread 'main' panicked at 'initializiation failed; exception backtrace above', vm/src/vm.rs:537:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: rustpython_vm::vm::VirtualMachine::_py_panic_failed
             at vm/src/vm.rs:537
  14: rustpython_vm::vm::VirtualMachine::expect_pyresult::{{closure}}
             at vm/src/vm.rs:545
  15: core::result::Result<T,E>::unwrap_or_else
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:848
  16: rustpython_vm::vm::VirtualMachine::expect_pyresult
             at vm/src/vm.rs:545
  17: rustpython_vm::vm::VirtualMachine::initialize
             at vm/src/vm.rs:268
  18: rustpython_vm::vm::VirtualMachine::new
             at vm/src/vm.rs:217
  19: rustpython::main
             at src/main.rs:39
  20: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  24: std::panicking::try
             at src/libstd/panicking.rs:281
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Same error trying `cargo run demo.py`

**Comment by eukap** [comment]
Try to set the RUSTPYTHONPATH environment variable:

`$ export RUSTPYTHONPATH=~/GIT/RustPython/Lib`

**Comment by alanjds** [comment]
Yes, this works.

I would send a PR including such line on the README, but looks like unintended to depend on it to have `cargo run` to work.

Options:
1. The examples need to change to include the explicit `RUSTPYTHONPATH` setup
2. When no `RUSTPYTHONPATH` is set, a reasonable one should be implied, maybe with a warning. (my preferred one for now)
3. The bare minimum `cargo run` should work without the stdlib available, as CPython does. (my least liked option)

**Comment by mireille-raad** [comment]
Do you think we can use the rustpython.github.io blog? 

We can write the fix for this README issue, but also for other stuff in a general troubleshooting article. If you think it is a good idea. I am happy to start it.

**Comment by dralley** [comment]
```
[dalley@localhost RustPython]$ echo $RUSTPYTHONPATH 

[dalley@localhost RustPython]$ cargo run demo.py
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rustpython demo.py`
Hello, RustPython!
```

I don't think the README issue is still a problem anymore
