### ISSUE TITLE
`whats_left.sh` broken with "AttributeError: module 'numbers' has no attribute 'Number'"

### ISSUE THREAD

**Issue by alanjds** [RustPython/RustPython#1874]
Tried on a virtualenv Python 3.7 just for RustPython:

The important part:
```python
===== MODULES =====
Traceback (most recent call last):
  File "tests/snippets/whats_left_modules.py", line 33, in <module>
    rustpymods
  File "tests/snippets/whats_left_modules.py", line 29, in <lambda>
    set(dir(__import__(mod)))
  File "_frozen_importlib", line 1093, in __import__
  File "_frozen_importlib", line 1014, in _gcd_import
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 975, in _find_and_load_unlocked
  File "_frozen_importlib", line 686, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 677, in _load_unlocked
  File "_frozen_importlib", line 671, in _load_unlocked
  File "_frozen_importlib_external", line 788, in exec_module
  File "_frozen_importlib", line 219, in _call_with_frames_removed
  File "/home/alanjds/src/git/RustPython/Lib/decimal.py", line 8, in <module>
    from _pydecimal import *
  File "/home/alanjds/src/git/RustPython/Lib/_pydecimal.py", line 3886, in <module>
    _numbers.Number.register(Decimal)
AttributeError: module 'numbers' has no attribute 'Number'
```

The full output:

```console
$ ./whats_left.sh 
    Finished release [optimized] target(s) in 0.07s
===== METHODS =====
bool.__init_subclass__
bool.__str__ (inherited)
bytearray.__alloc__
bytearray.__getattribute__ (inherited)
bytearray.__iadd__
bytearray.__init__ (inherited)
bytearray.__init_subclass__
bytearray.__ne__ (inherited)
bytearray.__reduce__ (inherited)
bytearray.__reduce_ex__ (inherited)
bytearray.__str__ (inherited)
bytes.__getattribute__ (inherited)
bytes.__getnewargs__
bytes.__init_subclass__
bytes.__ne__ (inherited)
bytes.__str__ (inherited)
complex.__format__ (inherited)
complex.__ge__ (inherited)
complex.__getattribute__ (inherited)
complex.__gt__ (inherited)
complex.__init_subclass__
complex.__le__ (inherited)
complex.__lt__ (inherited)
complex.__ne__ (inherited)
complex.__str__ (inherited)
dict.__doc__ (inherited)
dict.__ge__ (inherited)
dict.__getattribute__ (inherited)
dict.__gt__ (inherited)
dict.__init_subclass__
dict.__le__ (inherited)
dict.__lt__ (inherited)
enumerate.__doc__ (inherited)
enumerate.__getattribute__ (inherited)
enumerate.__init_subclass__
enumerate.__reduce__ (inherited)
filter.__getattribute__ (inherited)
filter.__init_subclass__
filter.__reduce__ (inherited)
float.__getattribute__ (inherited)
float.__getformat__
float.__getnewargs__
float.__init_subclass__
float.__set_format__
float.__str__ (inherited)
frozenset.__getattribute__ (inherited)
frozenset.__init_subclass__
frozenset.__reduce__ (inherited)
int.__getattribute__ (inherited)
int.__getnewargs__
int.__init_subclass__
int.__str__ (inherited)
list.__getattribute__ (inherited)
list.__init__ (inherited)
list.__init_subclass__
map.__getattribute__ (inherited)
map.__init_subclass__
map.__reduce__ (inherited)
memoryview.__delitem__
memoryview.__doc__ (inherited)
memoryview.__enter__
memoryview.__eq__ (inherited)
memoryview.__exit__
memoryview.__ge__ (inherited)
memoryview.__getattribute__ (inherited)
memoryview.__gt__ (inherited)
memoryview.__init_subclass__
memoryview.__le__ (inherited)
memoryview.__lt__ (inherited)
memoryview.__ne__ (inherited)
memoryview.__repr__ (inherited)
memoryview.__setitem__
memoryview.c_contiguous
memoryview.cast
memoryview.contiguous
memoryview.f_contiguous
memoryview.format
memoryview.hex
memoryview.itemsize
memoryview.nbytes
memoryview.ndim
memoryview.readonly
memoryview.release
memoryview.shape
memoryview.strides
memoryview.suboffsets
memoryview.tobytes
memoryview.tolist
range.__getattribute__ (inherited)
range.__init_subclass__
set.__getattribute__ (inherited)
set.__init__ (inherited)
set.__init_subclass__
set.__reduce__ (inherited)
slice.__doc__ (inherited)
slice.__getattribute__ (inherited)
slice.__init_subclass__
slice.__reduce__ (inherited)
str.__getattribute__ (inherited)
str.__getnewargs__
str.__init_subclass__
super.__init__ (inherited)
super.__init_subclass__
super.__self__
super.__self_class__
super.__thisclass__
tuple.__getattribute__ (inherited)
tuple.__getnewargs__
tuple.__init_subclass__
object.__init_subclass__
object.__sizeof__
zip.__doc__ (inherited)
zip.__getattribute__ (inherited)
zip.__init_subclass__
zip.__reduce__ (inherited)
classmethod.__init__ (inherited)
classmethod.__init_subclass__
classmethod.__isabstractmethod__
staticmethod.__doc__ (inherited)
staticmethod.__func__
staticmethod.__init__ (inherited)
staticmethod.__init_subclass__
staticmethod.__isabstractmethod__
property.__getattribute__ (inherited)
property.__init__ (inherited)
property.__init_subclass__
property.__isabstractmethod__
Exception.__doc__ (inherited)
Exception.__init__ (inherited)
Exception.__init_subclass__
Exception.__new__ (inherited)
BaseException.__delattr__ (inherited)
BaseException.__doc__ (inherited)
BaseException.__getattribute__ (inherited)
BaseException.__init_subclass__
BaseException.__reduce__ (inherited)
BaseException.__setattr__ (inherited)
BaseException.__setstate__
NoneType.__doc__ (inherited)
NoneType.__init_subclass__
bytearray_iterator.__doc__ (inherited)
bytearray_iterator.__getattribute__ (inherited)
bytearray_iterator.__init_subclass__
bytearray_iterator.__length_hint__
bytearray_iterator.__reduce__ (inherited)
bytearray_iterator.__setstate__
bytes_iterator.__doc__ (inherited)
bytes_iterator.__getattribute__ (inherited)
bytes_iterator.__init_subclass__
bytes_iterator.__length_hint__
bytes_iterator.__reduce__ (inherited)
bytes_iterator.__setstate__
dict_keyiterator.__doc__ (inherited)
dict_keyiterator.__getattribute__ (inherited)
dict_keyiterator.__init_subclass__
dict_keyiterator.__reduce__ (inherited)
dict_valueiterator.__doc__ (inherited)
dict_valueiterator.__getattribute__ (inherited)
dict_valueiterator.__init_subclass__
dict_valueiterator.__reduce__ (inherited)
dict_itemiterator.__doc__ (inherited)
dict_itemiterator.__getattribute__ (inherited)
dict_itemiterator.__init_subclass__
dict_itemiterator.__reduce__ (inherited)
dict_values.__doc__ (inherited)
dict_values.__getattribute__ (inherited)
dict_values.__init_subclass__
dict_items.__and__
dict_items.__contains__
dict_items.__doc__ (inherited)
dict_items.__eq__ (inherited)
dict_items.__ge__ (inherited)
dict_items.__getattribute__ (inherited)
dict_items.__gt__ (inherited)
dict_items.__hash__ (inherited)
dict_items.__init_subclass__
dict_items.__le__ (inherited)
dict_items.__lt__ (inherited)
dict_items.__ne__ (inherited)
dict_items.__or__
dict_items.__rand__
dict_items.__ror__
dict_items.__rsub__
dict_items.__rxor__
dict_items.__sub__
dict_items.__xor__
dict_items.isdisjoint
set_iterator.__doc__ (inherited)
set_iterator.__getattribute__ (inherited)
set_iterator.__init_subclass__
set_iterator.__reduce__ (inherited)
list_iterator.__doc__ (inherited)
list_iterator.__getattribute__ (inherited)
list_iterator.__init_subclass__
list_iterator.__reduce__ (inherited)
list_iterator.__setstate__
range_iterator.__doc__ (inherited)
range_iterator.__getattribute__ (inherited)
range_iterator.__init_subclass__
range_iterator.__length_hint__
range_iterator.__reduce__ (inherited)
range_iterator.__setstate__
str_iterator.__doc__ (inherited)
str_iterator.__getattribute__ (inherited)
str_iterator.__init_subclass__
str_iterator.__length_hint__
str_iterator.__reduce__ (inherited)
str_iterator.__setstate__
tuple_iterator.__doc__ (inherited)
tuple_iterator.__getattribute__ (inherited)
tuple_iterator.__init_subclass__
tuple_iterator.__length_hint__
tuple_iterator.__reduce__ (inherited)
tuple_iterator.__setstate__
===== MODULES =====
Traceback (most recent call last):
  File "tests/snippets/whats_left_modules.py", line 33, in <module>
    rustpymods
  File "tests/snippets/whats_left_modules.py", line 29, in <lambda>
    set(dir(__import__(mod)))
  File "_frozen_importlib", line 1093, in __import__
  File "_frozen_importlib", line 1014, in _gcd_import
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 975, in _find_and_load_unlocked
  File "_frozen_importlib", line 686, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 677, in _load_unlocked
  File "_frozen_importlib", line 671, in _load_unlocked
  File "_frozen_importlib_external", line 788, in exec_module
  File "_frozen_importlib", line 219, in _call_with_frames_removed
  File "/home/alanjds/src/git/RustPython/Lib/decimal.py", line 8, in <module>
    from _pydecimal import *
  File "/home/alanjds/src/git/RustPython/Lib/_pydecimal.py", line 3886, in <module>
    _numbers.Number.register(Decimal)
AttributeError: module 'numbers' has no attribute 'Number'
```

**Comment by youknowone** [comment]
It seems it is fixed now. Please reopen this issue if it is not solved
