### ISSUE TITLE
Interpreter crashes due to unitialized value in type initialization

### ISSUE THREAD

**Issue by snoop2head** [RustPython/RustPython#1969]
## Summary

* Similar to #1829 issue.
* Environment variable needs to be explicitly specified for README.md document for rustpython command on the shell.

### System Information
* MacOS Catalina version 10.15.5
* rustc 1.44.1 
* RustPython 0.1.1
* Zsh shell

### How to replicate the error
* I've tried to run following command on the shell and expected to get the result specified in [rustpython guideline](https://github.com/RustPython/RustPython#usage)
```
$ cargo install rustpython
$ rustpython
Welcome to the magnificent Rust Python interpreter
>>>>>
```
* Accordingly, I've ran the following command
```
$ cargo install rustpython
```
* After the installation is complete, I've restarted the shell.
* However, the command rustpython on the shell yielded
```
$ rustpython
thread 'main' panicked at 'attempted to leave type `pyobject::PyRef<obj::objtype::PyClass>` uninitialized, which is invalid', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/mem/mod.rs:661:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
* After adding "RUST_BACKTRACE=1" to the .zshrc file for configuring environment variable, it yielded the following error
```
thread 'main' panicked at 'attempted to leave type `pyobject::PyRef<obj::objtype::PyClass>` uninitialized, which is invalid', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/mem/mod.rs:661:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: rustpython_vm::pyobject::PyContext::new
  10: rustpython_vm::vm::VirtualMachine::new
  11: rustpython::main
  12: std::rt::lang_start::{{closure}}
  13: std::rt::lang_start_internal
  14: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
* After replacing the environment variable with "RUST_BACKTRACE=full", it yielded the following error.
```
thread 'main' panicked at 'attempted to leave type `pyobject::PyRef<obj::objtype::PyClass>` uninitialized, which is invalid', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/mem/mod.rs:661:5
stack backtrace:
   0:        0x1045a543f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ad47541fb823094
   1:        0x1045cbc8e - core::fmt::write::he23e9bd6497f06c3
   2:        0x10459e327 - std::io::Write::write_fmt::h91528f1131e6004e
   3:        0x1045a731a - std::panicking::default_hook::{{closure}}::h1983f014a45a477e
   4:        0x1045a705c - std::panicking::default_hook::hb0d9b93b5be8b120
   5:        0x1045a78e8 - std::panicking::rust_panic_with_hook::h9f3faafe0983de5c
   6:        0x1045a74b2 - rust_begin_unwind
   7:        0x1045dd83f - core::panicking::panic_fmt::h0a2d1b3ca0b14316
   8:        0x1045dd797 - core::panicking::panic::hfb3ef93dcafb964c
   9:        0x10418ca1c - rustpython_vm::pyobject::PyContext::new::h11369a8a71762d64
  10:        0x104204dc4 - rustpython_vm::vm::VirtualMachine::new::h83e6d6fcc6e9aa39
  11:        0x104124ece - rustpython::main::h106698688eb8909d
  12:        0x10412eab6 - std::rt::lang_start::{{closure}}::haa1d28624a71ea0e
  13:        0x1045a7c49 - std::rt::lang_start_internal::h795af50241e12334
  14:        0x1041282f9 - main
```
## Unresolved Questions

This is similar to #1829 issue.

**Comment by coolreader18** [comment]
:grimacing: this looks like it's something to do with our use of `mem::uninitialized`; I'll look into it.

**Comment by coolreader18** [comment]
Oh, this is because our old version that's on crates.io had undefined behavior, the version on master should work fine. @snoop2head try `cargo install --force https://github.com/RustPython/RustPython`

We really need to cut a new update :grimacing:

**Comment by snoop2head** [comment]
😅Should I file this error for [crates.io-index](https://github.com/rust-lang/crates.io-index) or [cargo](https://github.com/rust-lang/cargo) repository? 

```
$ cargo install --force https://github.com/RustPython/RustPython
    Updating crates.io index
error: could not find `https://github.com/RustPython/RustPython` in registry `https://github.com/rust-lang/crates.io-index
```

I have referred to [the issue on the cargo](https://github.com/rust-lang/cargo/issues/4007), but clearing registry folder does not seem to work.

Any suggestions to configure cargo? Or any other possible causes for this error?

**Comment by coolreader18** [comment]
Whoops, sorry, I just forgot the syntax. It's `cargo install --force --git https://github.com/RustPython/RustPython`

**Comment by snoop2head** [comment]
Along with the commands above, I additionally chose rustpython out of rustpython and rustpython_freeze package. The command is the following:
``` shell
cargo install --force --git https://github.com/RustPython/RustPython rustpython
```

**However, it yields an error of the following:**
```
   Compiling rustpython-derive v0.1.1 (/Users/noopy/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/5f5478d/derive)
error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
   --> vm/src/stdlib/thread.rs:125:9
    |
125 |         self.mu.unlock()
    |         ^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior

error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
   --> vm/src/stdlib/thread.rs:182:9
    |
182 |         self.mu.unlock()
    |         ^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior

error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
   --> vm/src/stdlib/thread.rs:240:17
    |
240 |                 lock.mu.unlock()
    |                 ^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: consult the function's documentation for information on how to avoid undefined behavior

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0133`.
error: failed to compile `rustpython v0.1.1 (https://github.com/RustPython/RustPython#5f5478db)`, intermediate artifacts can be found at `/var/folders/f8/9hn0rsx125vf87jp8_skr1l40000gn/T/cargo-installRDU0Yr`

Caused by:
  could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.
```
It did successfully downloaded 60 crates. Is it the compiler that has caused the problem?

**Comment by coolreader18** [comment]
Oh, it's a git dependency I believe. That would be failing on master as well, I believe, I'll fix that.

**Comment by coolreader18** [comment]
You could try adding the `--locked` flag to the install command to fix it.

**Comment by snoop2head** [comment]
```
$ cargo install --force --git https://github.com/RustPython/RustPython rustpython --locked
Replaced package `rustpython v0.1.1` with `rustpython v0.1.1 (https://github.com/RustPython/RustPython#ff6935b3)` (executable `rustpython`)

$ rustpython
couldn't init zipimport
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
No previous history.
>>>>> print("finally working!")
```
Thanks for your help! It finally works 😆 Shall I close the issue?

**Comment by coolreader18** [comment]
Yeah, I think we just need to cut a new version to fix these problems; we're waiting on Amanieu/parking_lot#239 for that since you can't publish to crates.io when you have git dependencies.
