### ISSUE TITLE
Payload conflicts

### ISSUE THREAD

**Issue by skinny121** [RustPython/RustPython#1979]
Currently you are allowed to have the following:
```python
class Weird(str, int):
    pass
```
But this causes issues using using instances of this class as both `str` and `int` expect the payload to be `PyString` and `PyInt` respectively, but the object can only have a single payload.
```python
>>>>> 2 + Weird()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Unexpected payload for type "Weird"
```

CPython deals with this by raising an error during class construction time:
```python
>>> class Weird(str, int):
...     pass

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: multiple bases have instance lay-out conflict
```

I feel we should do a similar thing by detecting when bases have different payloads.

This also comes up in `__class__` assignment, the following is CPython behavior:
```python
>>> class A(str): pass
... 
>>> class B(int): pass
... 
>>> A().__class__ = B
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __class__ assignment: 'B' object layout differs from 'A'

```

**Comment by coolreader18** [comment]
We could probably do something with a `TypeId` stored in `PyClass`

**Comment by arihant2math** [comment]
This no longer occurs:
```
> python tmp.py
Traceback (most recent call last):
  File "D:\Documents\Programming\GitHub\RustPython\tmp.py", line 1, in <module>
    class Weird(str, int):
        pass
TypeError: multiple bases have instance lay-out conflict

> ./target/release/rustpython tmp.py
Traceback (most recent call last):
  File "tmp.py", line 1, in <module>
    class Weird(str, int):
TypeError: multiple bases have instance layout conflict
```

**Comment by youknowone** [comment]
@arihant2math Thank you for checking!
