### ISSUE TITLE
unittest test_support.py Failed

### ISSUE THREAD

**Issue by qingshi163** [RustPython/RustPython#2241]
Env:
Manjaro 5.8.6-1
rustc 1.46.0

The unittest from test_support.py gives me the error on master branch.
Follow the test, I find out if we call socket.bind with the address 'localhost', than we fail, but CPython will treat it as 127.0.0.1.

```
======================================================================
ERROR: test_HOST (__main__.TestSupport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Lib/test/test_support.py", line 94, in test_HOST
    s = socket.create_server((support.HOST, 0))
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/socket.py", line 898, in create_server
    raise
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/socket.py", line 889, in create_server
    (err.strerror, address)
AttributeError: 'OSError' object has no attribute 'strerror'

======================================================================
ERROR: test_bind_port (__main__.TestSupport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Lib/test/test_support.py", line 104, in test_bind_port
    support.bind_port(s)
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/test/support/__init__.py", line 796, in bind_port
    sock.bind((host, 0))
OSError: Address family not supported by protocol (os error 97)

======================================================================
ERROR: test_find_unused_port (__main__.TestSupport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Lib/test/test_support.py", line 98, in test_find_unused_port
    port = support.find_unused_port()
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/test/support/__init__.py", line 759, in find_unused_port
    port = bind_port(tempsock)
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/test/support/__init__.py", line 759, in find_unused_port
    port = bind_port(tempsock)
  File "/home/skz/Projects/RustPython/vm/pylib-crate/Lib/test/support/__init__.py", line 796, in bind_port
    sock.bind((host, 0))
OSError: Address family not supported by protocol (os error 97)
```

**Comment by awoimbee** [comment]
Quick way to recreate the socket error:

```python
import socket
import sys

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    s.bind(('localhost', 5555))
except socket.error as msg:
    print(f'Bind failed: {msg}')
    sys.exit()
print('Socket bind complete')

```

[std::net::ToSocketAddrs](https://doc.rust-lang.org/nightly/std/net/trait.ToSocketAddrs.html) does its job. `host: "localhost" result: Ok(IntoIter([[::1]:5555, 127.0.0.1:5555]))`

Then `get_addr()` just reads the first one (which is IPv6 on my system).
-> We then pass this IPv6 address to an IPv4 socket <-

So `get_addr()` just need to be aware of PySocket::family and to filter incompatible IPs

I'm gonna create a PR if that's Ok.

**Comment by frazar** [comment]
Also note that is issue is not caught in CI because [this line](https://github.com/RustPython/RustPython/blob/7eb9335d193aa253e25952451ac1500453cab386/.github/workflows/ci.yaml#L19) sets `RUSTPYTHON_NO_IPV6=1`, thus making `get_addr()` filter out the IPv6 address.

**Comment by coolreader18** [comment]
Yeah, that was a workaround in #2179 because the CI environment doesn't support IPv6 (actions/virtual-environments#668). I didn't realize it was because of the family of the socket object, or I didn't connect the dots at least. Please feel free to make a PR @awoimbee, it'd be great to get rid of this hack!
