### ISSUE TITLE
Arguments to `compile`

### ISSUE THREAD

**Issue by nomeata** [RustPython/RustPython#2390]
## Feature

Trying to sandbox one of my projects in `RustPython` and  wasm, I ran into this difference in behaviour:

```
$ python3 -c 'compile("",filename = "bot-code.py", mode = "exec")'
$ wasmtime run rustpython.wasm -- -c 'compile("",filename = "bot-code.py", mode = "exec")'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected at least 0 arguments (1 given)
```

This is `rustpython.wasm` 0.1.3 from https://wapm.io/package/rustpython#explore.

## Python Documentation

https://docs.python.org/3/library/functions.html#compile

**Comment by nomeata** [comment]
Also, this error message looks a bit … odd:
```
$ wasmtime run rustpython.wasm -- -c 'compile(source = "",filename = "bot-code.py", mode = "exec")'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected at least 0 arguments (0 given)
```

**Comment by nomeata** [comment]
Confirmed with latest `master`, built with `cargo build --release --target wasm32-wasi --features="freeze-stdlib"`

**Comment by nomeata** [comment]
This is pure cargo-culting, but
```diff
diff --git a/vm/src/builtins/make_module.rs b/vm/src/builtins/make_module.rs
index 6c7f4a9a..2af6882a 100644
--- a/vm/src/builtins/make_module.rs
+++ b/vm/src/builtins/make_module.rs
@@ -103,11 +103,11 @@ mod decl {
     #[derive(FromArgs)]
     #[allow(dead_code)]
     struct CompileArgs {
-        #[pyarg(positional)]
+        #[pyarg(any)]
         source: Either<PyStrRef, PyBytesRef>,
-        #[pyarg(positional)]
+        #[pyarg(any)]
         filename: PyStrRef,
-        #[pyarg(positional)]
+        #[pyarg(any)]
         mode: PyStrRef,
         #[pyarg(any, optional)]
         flags: OptionalArg<PyIntRef>,
```
_seems_ to fix it.

**Comment by coolreader18** [comment]
Yeah, I think that would fix the issue of keyword arguments! I generally use `compile()` with only positional arguments, so I guess I haven't run into this bug. Feel free to submit a PR/patch with that change! :)
