### ISSUE TITLE
[BUG] decoding bytes error

### ISSUE THREAD

**Issue by darleybarreto** [RustPython/RustPython#2391]
When running
```python
b'-\xff'.decode(sys.getfilesystemencoding(), 'surrogateescape')
```
On both PyPy and CPython, I get 
```python
'-\udcff'
```
In RustPython
```python
Traceback (most recent call last):
  File "/home/darley/Documents/Repositories/RustPython/vm/pylib-crate/Lib/_codecs.py", line 567, in lookup_error
    err_handler = codec_error_registry[errors]
KeyError: surrogateescape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 140, in decode
    res = codec[1](obj, errors)
  File "/RustPython/vm/pylib-crate/Lib/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 463, in __call__
    return self._f(*args, **kwargs)
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 177, in utf_8_decode
    res, consumed = PyUnicode_DecodeUTF8Stateful(data, len(data), errors, final)
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 1133, in PyUnicode_DecodeUTF8Stateful
    s,  startinpos, endinpos)
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 1059, in unicode_call_errorhandler
    errorHandler = lookup_error(errors)
  File "/RustPython/vm/pylib-crate/Lib/_codecs.py", line 569, in lookup_error
    raise LookupError("unknown error handler name %s"%errors)
LookupError: unknown error handler name surrogateescape
```
I found this when I tried to use [os_helper.py](https://github.com/python/cpython/blob/master/Lib/test/support/os_helper.py)

**Comment by coolreader18** [comment]
Yeah, we don't support surrogateescape at the moment on account of using utf8 strings internally; we should probably mention that somewhere in the README or something.

**Comment by verhovsky** [comment]
See #935

**Comment by arihant2math** [comment]
No longer applicable, this can be closed.

**Comment by youknowone** [comment]
To close this issue, I'd like to add the reported case under extra_tests
