### ISSUE TITLE
Conversion of objects with __index__() to bin, hex, oct

### ISSUE THREAD

**Issue by ishigoya** [RustPython/RustPython#2583]
## Feature

At present, objects with the `__index__()` method cannot be converted to binary, hex or oct strings.

## Python Documentation

From the [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__index__):

> object.\_\_index\_\_(self)
> 
> Called to implement operator.index(), and whenever Python needs to losslessly convert the numeric object to an integer object (such as in slicing, or in the built-in bin(), hex() and oct() functions). Presence of this method indicates that the numeric object is an integer type. Must return an integer.

## Example

Behaviour in Python:

```python
Ꮲ > class CustomInt:
...     def __index__(self):
...             return 100
...
Ꮲ > a = CustomInt()
Ꮲ > import operator
Ꮲ > operator.index(a)
100
Ꮲ > int(a)
100
Ꮲ > float(a)
100.0
Ꮲ > complex(a)
(100+0j)
Ꮲ > bin(a)
'0b1100100'
Ꮲ > hex(a)
'0x64'
Ꮲ > oct(a)
'0o144'
```

But fails for bin, hex and oct in rustpython:

```python
$ rustpython
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> class CustomInt:
.....     def __index__(self):
.....             return 100
.....
>>>>> a = CustomInt()
>>>>> import operator
>>>>> operator.index(a)
100
>>>>> int(a)
100
>>>>> float(a)
100.0
>>>>> complex(a)
(100+0j)
>>>>> bin(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected type 'int', not 'CustomInt'
>>>>> hex(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected type 'int', not 'CustomInt'
>>>>> oct(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected type 'int', not 'CustomInt'
```

## Failing tests

I think this might be causing some tests to fail. For example, the test below from test_zlib uses an object with the `__index__()` method:

```
ERROR: test_custom_bufsize (__main__.CompressTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_zlib.py", line 218, in test_custom_bufsize
    self.assertEqual(zlib.decompress(compressed, 15, CustomInt()), data)
TypeError: Expected type 'int', not 'CustomInt'
```

**Comment by ishigoya** [comment]
I'm working to get my head around the behaviour of the `__index__` method in
CPython compared with RustPython. [PEP 357](https://www.python.org/dev/peps/pep-0357) has been a really useful starting point for that.

Possibly not directly related, but I also encountered the issue below relating to the `__index__` method.

CPython:

```python
Ꮲ > class MyInt(str):
...     def __index__(self):
...             return 12
...
Ꮲ > a = MyInt()
Ꮲ > int(a)
12
```

RustPython:

```python
>>>>> class MyInt(str):
..... 	def __index__(self):
..... 		return 12
.....
>>>>> a = MyInt()
>>>>> int(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: ''
```

**Comment by ishigoya** [comment]
I've come up with a possible solution to this issue. I'll explain the background a bit, for my own learning if nothing else!

-----

#### The Issue

As described in PEP 357, objects with a `__index__` method that returns an integer can be treated as integers.

In CPython, the `PyNumber_Index` function is used to verify the presence of a valid `__index__` function. For example, below is the code used by the bin function:

```C
PyObject *
PyNumber_ToBase(PyObject *n, int base)
{
    if (!(base == 2 || base == 8 || base == 10 || base == 16)) {
        PyErr_SetString(PyExc_SystemError,
                        "PyNumber_ToBase: base must be 2, 8, 10 or 16");
        return NULL;
    }
    PyObject *index = PyNumber_Index(n);
    if (!index)
        return NULL;
    PyObject *res = _PyLong_Format(index, base);
    Py_DECREF(index);
    return res;
}
```

This is used in many parts of the CPython codebase where an integer is expected. 

In RustPython, the `to_index` functions appear to be fulfilling a similar role, unpacking PyObjectRef objects and (coincidentally?) verifying that they are ints.

The issue this time originates from the fact that the bin, oct and hex functions take PyIntRef objects as arguments, and therefore bypass the informal `__index__`-based type checking performed by the `to_index` functions. Similarly, in the failed zlib test, an `__index__`-defined integer was passed to the bufsize keyword, which takes a `usize` value. In both of these cases, type checking takes place via the `TryFromObject` trait. At present, this mechanism only compares the type of the target and passed objects, not considering other factors. As a result, these `__index__`-defined integers are not treated as integers.

#### Possible Solution

As a tentative solution, I added a `special_retrieve` function to the `PyValue` trait. Signature:

```rust
special_retrieve(vm: &VirtualMachine, obj: PyObjectRef) -> Option<PyResult<PyRef<Self>>>
```

For PyInt, I defined the function in a similar way to the existing `to_index` function: it verifies that the `__index__` method is defined and returns an integer. In this way, the `TryFromObject`-based type checker correctly identified `__index__`-defined integers.

#### Alternatives

One alternative method of providing similar trait-based type checking would be by creating another trait with similar functionality to the `PyValue` trait, and applying it only to PyInt. However, it seems like this would be a lot of work, and lead to a lot of duplication of code.

Another alternative might be to use [specialisation](https://github.com/rust-lang/rust/issues/31844) to define a separate type-checking function on PyInt.

#### Effects

As the conditional branch running the `special_retrieve` function only runs when the current type checking fails, I think the performance effect on type checking would be minimal.

The `special_retrieve` function could also be used to cover any other special cases that arise in trait-based type checking.

This change may also permit simplifying the `to_index` functions, which could improve performance in places where it is used (such as in the slice builtin).

-----

I'm still getting to grips with Rust and the codebase, so I recognise the chance I've missed something here is fairly high. 
In any case, it's been quite a fun rabbit hole!

Here's the draft PR: #2592
