### ISSUE TITLE
Missing dataclasses module

### ISSUE THREAD

**Issue by oroppas** [RustPython/RustPython#2623]
## Feature

[rich](https://github.com/willmcgugan/rich) depends on `dataclasses`

## Python Documentation

https://docs.python.org/3/library/dataclasses.html?highlight=dataclasses#module-dataclasses

**Comment by moreal** [comment]
This issue is not able to solve until https://github.com/RustPython/RustPython/issues/2869 solved.

`dataclasses` module calls `inspect._signature_from_callable` and it compares `__new__` built-in method.
Though empty class doesn't have additional `__new__` method definition but RustPython implementation always bind new bound method for each types.

## References

https://github.com/RustPython/RustPython/blob/8cf3506f53bb3d7748d86bc6e20d6dd279458cce/vm/src/pyobject.rs#L391-L397

https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Lib/inspect.py#L2367-L2368:
``` python
# _signature_from_callable
                if (obj.__init__ is object.__init__ and
                    obj.__new__ is object.__new__):
```

**Comment by moreal** [comment]
Sadly, though #2869 was resolved, it doesn't work because there #2410 is not resolved  😿

```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> import dataclasses
>>>>> @dataclasses.dataclass
..... class A:
.....   s: str
..... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/dataclasses.py", line 1000, in dataclass
    return wrap(cls)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/dataclasses.py", line 992, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/dataclasses.py", line 972, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 2843, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 2370, in _signature_from_callable
    return sigcls.from_callable(object)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 2843, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 2297, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/home/moreal/github/RustPython/RustPython/vm/pylib-crate/Lib/inspect.py", line 2107, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <class 'object'>
>>>>> 
```

**Comment by moreal** [comment]
Though #2410 was resolved by #2904, the new bug #2917, #2918 appeared. I started to work on them.

**Comment by moreal** [comment]
Though #2917 and #2918 seem resolved by #2633 and #2924, a new bug which `<KEY> in <TYPE>.__dict__` try to find `<KEY>` even the base types. I'm trying to fix the bug through #2932.

**Comment by oroppas** [comment]
It appears https://github.com/RustPython/RustPython/commit/2c3460244af9e00bc24d4af75cd931a66f166030 add enough `dataclasses` support such that we can run basic [rich](https://github.com/willmcgugan/rich)

![image](https://user-images.githubusercontent.com/885380/132287658-c54385e7-041d-4473-a340-3a6136a67d83.png)

This is really awesome! Thank you.

**Comment by Snowapril** [comment]
Cool! 😊
