### ISSUE TITLE
"certificate verify failed" when installing pip

### ISSUE THREAD

**Issue by domdfcoding** [RustPython/RustPython#2629]
Hi,

I have built and installed RustPython from source using cargo:

```console
cargo install --git https://github.com/RustPython/RustPython --features ssl
```

However, when I attempt to install pip using the `rustpython --install-pip` command I am faced with the following error:

<details>
 <summary>Long Traceback</summary>

```python traceback
downloading get-pip.py...
Traceback (most recent call last):
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 1351, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 964, in send
    self.connect()
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 507, in wrap_socket
    session=session
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 1043, in _create
    raise
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 1311, in do_handshake
    self.settimeout(timeout)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
SSLError: (134, 'certificate verify failed (_ssl.c:1913)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frozen", line 3, in <module>
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 1394, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 1357, in do_open
    raise
  File "/home/domdf/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/b6aa690/vm/pylib-crate/Lib/urllib/request.py", line 1353, in do_open
    raise URLError(err)
URLError: (134, 'certificate verify failed (_ssl.c:1913)')

```

</details>

I can reproduce this within RustPython with other HTTPS websites, so I don't think the issue is specific to downloading `get-pip.py`.

I can successfuly make HTTPS connections by using the [pem file from certifi](https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem). 

Comparing the output of `ssl.get_default_verify_paths()` between CPython and RustPython, it seems `capath` is unset and the other paths point to temporary directories used by cargo which no longer exist. I think one or both of those is the problem.

**CPython**

```
DefaultVerifyPaths(cafile=None, capath='/usr/lib/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
```

**RustPython**

```
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/tmp/cargo-installEtyP0q/release/build/openssl-sys-1016fe0556eacb79/out/openssl-build/install/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/tmp/cargo-installEtyP0q/release/build/openssl-sys-1016fe0556eacb79/out/openssl-build/install/ssl/certs')
```

-----

I'm on Ubuntu 20.04 with the latest rust and cargo versions, and OpenSSL 1.1.1f

**Comment by coolreader18** [comment]
Oh, hmm, that's not optimal. But try running `cargo install` with the `OPENSSL_NO_VENDOR` option set, I think that should use the system openssl and correctly find the ca files.

**Comment by domdfcoding** [comment]
> But try running cargo install with the OPENSSL_NO_VENDOR option set

Ah, thanks. I wasn't aware of that option. I'll give it a go

**Comment by coolreader18** [comment]
Ohhh wait the actual issue is this:

https://github.com/RustPython/RustPython/blob/b6aa6900f69d15aa412cd450941c5fd488269f97/vm/src/stdlib/ssl.rs#L970-L973

The `openssl_probe` call should be in the first match arm.
