### ISSUE TITLE
get-pip.py fails

### ISSUE THREAD

**Issue by oroppas** [RustPython/RustPython#2648]
```
$ cargo run --features ssl --release 
    Finished release [optimized] target(s) in 0.17s
     Running `target/release/rustpython`
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>>
```

works like a charm but

```python
$ cargo run --features ssl --release ../get-pip.py
    Finished release [optimized] target(s) in 0.17s
     Running `target/release/rustpython ../get-pip.py`
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-21.1.1-py3-none-any.whl (1.5 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/cli/req_command.py", line 210, in wrapper
    raise
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/commands/install.py", line 445, in run
    return ERROR
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "/home/ryuta/packages/rustpython/rustpython/vm/pylib-crate/Lib/functools.py", line 593, in wrapper
    result = user_function(*args, **kwds)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/resolution/resolvelib/factory.py", line 261, in iter_index_candidate_infos
    hashes=hashes,
  File "/home/ryuta/packages/rustpython/rustpython/vm/pylib-crate/Lib/functools.py", line 569, in wrapper
    result = user_function(*args, **kwds)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/home/ryuta/packages/rustpython/rustpython/vm/pylib-crate/Lib/functools.py", line 569, in wrapper
    result = user_function(*args, **kwds)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/home/ryuta/packages/rustpython/rustpython/vm/pylib-crate/Lib/functools.py", line 298, in __call__
    return self.func(*self.args, *args, **keywords)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/collector.py", line 445, in _get_html_page
    _handle_get_page_fail(link, "timed out")
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/index/collector.py", line 137, in _get_html_response
    "Cache-Control": "max-age=0",
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_internal/network/session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/requests/adapters.py", line 531, in send
    raise
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 776, in urlopen
    self._put_conn(conn)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 761, in urlopen
    err = e
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 688, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/connectionpool.py", line 271, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/util/connection.py", line 31, in is_connection_dropped
    return False
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/util/connection.py", line 29, in is_connection_dropped
    return wait_for_read(sock, timeout=0.0)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/util/wait.py", line 146, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/util/wait.py", line 139, in wait_for_socket
    return wait_for_socket(*args, **kwargs)
  File "/tmp/tmpc26in8gz/pip.zip/pip/_vendor/urllib3/util/wait.py", line 99, in poll_wait_for_socket
    poll_obj.register(sock, mask)
TypeError: 'SSLSocket' object cannot be interpreted as an integer
```

**Comment by domdfcoding** [comment]
I can reproduce with a little snippet based on what urllib3 is doing:

```python
import socket, select
sock = socket.socket()
assert hasattr(sock, "fileno")
select.poll().register(sock)
```
```python traceback
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    select.poll().register(sock)
TypeError: 'socket' object cannot be interpreted as an integer
```

The docs for the "register" method say the first argument can be "either an integer, or an object with a fileno() method returning an int". 

I can track the exception within the rust code to 

https://github.com/RustPython/RustPython/blob/e05428851d84aaad88f3e8d2c3808837ac159cd2/vm/src/vm.rs#L842-L863

I think it's looking for an `__index__` method which the socket object doesn't have. Somewhere before then there needs to be a check for the `fileno` method and use that value going forwards.

-----

I was able to get past the error by adding an `__index__` method to `socket.socket`. However, I then hit another `TypeError` with the `select.poll.poll` method. The first argument (the timeout) may be a float in CPython, but RustPython raises

```python traceback
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by coolreader18** [comment]
I think I've got a fix for this; sorry the other one didn't actually work, I guess when I tested it `pip.whl` was already cached on my computer.

**Comment by oroppas** [comment]
Thank you for the quick fix!
