### ISSUE TITLE
--install-pip fails on Windows

### ISSUE THREAD

**Issue by oroppas** [RustPython/RustPython#2671]
```
C:\msys64\home\ryuta\packages\rustpython\rustpython>cargo run --features ssl --release -- --install-pip
    Finished release [optimized] target(s) in 0.69s
     Running `target\release\rustpython.exe --install-pip`
downloading get-pip.py...
Traceback (most recent call last):
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 1351, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 964, in send
    self.connect()
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 507, in wrap_socket
    session=session
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 1043, in _create
    raise
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 1311, in do_handshake
    self.settimeout(timeout)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
SSLError: (134, 'certificate verify failed (_ssl.c:1915)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frozen", line 3, in <module>
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 1394, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 1357, in do_open
    raise
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
URLError: (134, 'certificate verify failed (_ssl.c:1915)')
error: process didn't exit successfully: `target\release\rustpython.exe --install-pip` (exit code: 1)
```

**Comment by oroppas** [comment]
https://bugs.python.org/issue36011 may be related.

**Comment by oroppas** [comment]
After #3210, I see

```
C:\msys64\home\ryuta\packages\rustpython\rustpython>cargo run --release --features ssl -- --install-pip
   Compiling rustpython-vm v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython\vm)
   Compiling rustpython-stdlib v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython\stdlib)
   Compiling rustpython v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython)
    Finished release [optimized] target(s) in 1m 11s
     Running `target\release\rustpython.exe --install-pip`
downloading get-pip.py...
running get-pip.py...
Traceback (most recent call last):
  File "get-pip.py", line 24424, in <module>
  File "get-pip.py", line 143, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 121, in bootstrap
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\main.py", line 59, in main
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\main.py", line 55, in main
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\main_parser.py", line 58, in parse_command
  File "C:\msys64\home\ryuta\packages\rustpython\rustpython\Lib\optparse.py", line 1371, in parse_args
    values = self.get_default_values()
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\parser.py", line 279, in get_default_values
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\parser.py", line 277, in get_default_values
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\configuration.py", line 134, in load
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\configuration.py", line 256, in _load_config_files
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\configuration.py", line 359, in iter_config_files
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\configuration.py", line 75, in get_configuration_files
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\utils\appdirs.py", line 31, in site_config_dirs
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_vendor\appdirs.py", line 243, in site_config_dir
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_vendor\appdirs.py", line 138, in site_data_dir
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_vendor\appdirs.py", line 486, in _get_win_folder_from_registry
FileNotFoundError: (2, 'The system cannot find the file specified. (os error 2)')
error: process didn't exit successfully: `target\release\rustpython.exe --install-pip` (exit code: 1)C:\msys64\home\ryuta\packages\rustpython\rustpython>cargo run --release --features ssl -- --install-pip
   Compiling rustpython-vm v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython\vm)
   Compiling rustpython-stdlib v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython\stdlib)
   Compiling rustpython v0.1.2 (C:\msys64\home\ryuta\packages\rustpython\rustpython)
    Finished release [optimized] target(s) in 1m 11s
     Running `target\release\rustpython.exe --install-pip`
downloading get-pip.py...
running get-pip.py...
Traceback (most recent call last):
  File "get-pip.py", line 24424, in <module>
  File "get-pip.py", line 143, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 121, in bootstrap
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip\_internal\cli\main.py", line 59, in main
  File "C:\Users\ryuta\AppData\Local\Temp\tmpr4e6v5v0\pip.zip\pip
```

**Comment by oroppas** [comment]
`appdirs` is replaced by `platformdirs` 

https://github.com/pypa/pip/commit/ae6cf66c79734924544c4d5312dc0ca6072f324b#diff-8ff5175fdf2eb404b6eb6288021f0d4f1e33d7526c80b0ba471682208f26e293

**Comment by youknowone** [comment]
Finally it is working on windows!
