### ISSUE TITLE
super.__init__() always gets all arguments when inheriting from builtin class

### ISSUE THREAD

**Issue by verhovsky** [RustPython/RustPython#2693]
On CPython 3.9.5 I can inherit from `list` and take an extra argument before initializing the list

```pycon
>>> class MyList(list):
...     def __init__(self, initial_size=0):
...         self._initial_size = initial_size
...         super().__init__()
... 
>>> MyList(22)
[]
```

On latest RustPython it seems to pass all the arguments to `list()`, regardless of what I actually pass when invoking `__init__`

```pycon
>>>>> class MyList(list):
.....     def __init__(self, initial_size=0):
.....         self._initial_size = initial_size
.....         super().__init__()
..... 
>>>>> MyList(22)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not iterable
>>>>> 
>>>>> class MyList(list):
.....     def __init__(self, first, second, third):
.....         super().__init__([first])
..... 
>>>>> print(MyList(1, 2, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected at most 2 arguments (4 given)
>>>>>
```

It seems to work correctly if the base class is defined in Python

```pycon
>>>>> class A:
.....     def __init__(self):
.....         pass
..... 
>>>>> class B(A):
.....     def __init__(self, first_arg):
.....         super().__init__()
..... 
>>>>> print(B(1))
<B object at 0x137e8a660>
>>>>> 
```

**Comment by verhovsky** [comment]
duplicate of #1782
