### ISSUE TITLE
Package installation error with PIP

### ISSUE THREAD

**Issue by Paroxyste** [RustPython/RustPython#2721]
Rust : 1.53.0
Tested on : Solus 4.2 & Manjaro 21.0.7

## Feature

Hello when I try to install a package like flask or quart with pip with the command :

`rustpython -m pip install quart` or `rustpython -m pip install quart==0.15.1`

I get in return :

```python
    ERROR: Command errored out with exit status 1:
     command: /home/paroxyste/.cargo/bin/rustpython -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4xjw9igt/blinker_ac4121cc82b341d99b85a4bc758e4d83/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4xjw9igt/blinker_ac4121cc82b341d99b85a4bc758e4d83/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rx7meqzc
         cwd: /tmp/pip-install-4xjw9igt/blinker_ac4121cc82b341d99b85a4bc758e4d83/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/paroxyste/.local/lib/rustpython3.9/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/home/paroxyste/.local/lib/rustpython3.9/site-packages/setuptools/dist.py", line 38, in <module>
        from setuptools import windows_support
      File "/home/paroxyste/.local/lib/rustpython3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
    ModuleNotFoundError: No module named 'ctypes'
```

but if I install for example configparser it works perfectly.

The error mentioned above occurred with the packages :
- Flask
- Quart
- blinker
- asyncpg
- psycopg2
and more ...

During my research I came across an almost similar error `Python3: ImportError: No module named '_ctypes'` However this is not my case as this error can be solved by installing `libffi-devel` (and I did install it)

Also, when trying to install the cryptography package I got the following error:

```python
  ERROR: Command errored out with exit status 1:
   command: /home/paroxyste/.cargo/bin/rustpython /tmp/pip-standalone-pip-sdepgpwd/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hl4loo4j/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4'
       cwd: None
  Complete output (1 lines):
  [ERROR rustpython] can't open file '/tmp/pip-standalone-pip-sdepgpwd/__env_pip__.zip/pip': Not a directory (os error 20)

```

## Python Documentation

[Doc : ctypes python 3.9.6](https://docs.python.org/3/library/ctypes.html)

---

If you wish to have more details I am at your disposal.

Thanks to you!

**Comment by youknowone** [comment]
#2364

**Comment by youknowone** [comment]
windows_support.py is already fixed. The remaining bundled platformdirs issue will be tracked in other issue.
