### ISSUE TITLE
pip support in macos

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#2793]
```sh
$ rustpython --install-pip
downloading get-pip.py...
running get-pip.py...
Collecting pip
  Using cached pip-21.2.2-py3-none-any.whl (1.6 MB)
Collecting setuptools
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.2.2 setuptools-57.4.0 wheel-0.36.2
$ rustpython -m pip
~/.cargo/bin/rustpython: No module named pip
```

it looks like installed successfully, but still `no module named pip` happens

**Comment by holg** [comment]
Same for me, in the sys.path, there is an entry:
`/.local/lib/rustpython3.9/site-packages`
but this is empty and should contain the pip, setuptools and wheel packages.

**Comment by jamestwebber** [comment]
I just tried this and I get that output (i.e. a "success") but also a bunch of error messages:

```
(rustlang) ➜  RustPython git:(master) ./target/release/rustpython --install-pip
downloading get-pip.py...
running get-pip.py...
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/lib/python3.9/dist-packages
sysconfig: /usr/local/lib/rustpython3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/lib/python3.9/dist-packages
sysconfig: /usr/local/lib/rustpython3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/local/include/rustpython3.9/UNKNOWN
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting pip
  Downloading pip-21.2.3-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 684 kB/s 
Collecting setuptools
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /usr/local/include/python3.9/wheel
  sysconfig: /usr/local/include/rustpython3.9/wheel
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /usr/local/include/python3.9/setuptools
  sysconfig: /usr/local/include/rustpython3.9/setuptools
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /usr/local/include/python3.9/pip
  sysconfig: /usr/local/include/rustpython3.9/pip
Successfully installed pip-21.2.3 setuptools-57.4.0 wheel-0.36.2
```

As an aside, it'd be pretty sweet if it knew to install into my conda environment...

**Comment by secantsquared** [comment]
Not sure if this will help, but I was finally able to get this to work as expected (both install and ability to the executable to find and import the module) by passing the `--user` flag to the `--install-pip` flag provided in the projects documentation.  
Therefore, after building and installing the executable as outlined in the docs, I was able to adjust the pip installation step as follows:  

```bash
rustpython --install-pip --user
```

This had prompted the installation to be targeted to the user based `.local` directory in `$HOME`, instead of the corresponding system-wide equivalent location and once the installation finished, I was able to then have the executable find and import pip, subsequently producing the expected behavior.

**Comment by DimitrisJim** [comment]
Is pip workable on macos then? #3158 maybe solved it.

**Comment by youknowone** [comment]
Instead of silent failing, it shows error messages. So it is not solved but progressed!
```
cargo run --release --all-features -- --install-pip
    Finished release [optimized] target(s) in 0.56s
     Running `target/release/rustpython --install-pip`
downloading get-pip.py...
running get-pip.py...
Traceback (most recent call last):
  File "get-pip.py", line 24424, in <module>
    3YUtei%X>?y-E^v8JO928D02BZK00;m`Rt8fKnOFcn1pojH4gdff00000000000002Cfe{E30B~t=FJ
  File "get-pip.py", line 143, in main
    shutil.rmtree(tmpdir, ignore_errors=True)
  File "get-pip.py", line 139, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 139, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 115, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "get-pip.py", line 96, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/cli/base_command.py", line 12, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/configuration.py", line 21, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_internal/exceptions.py", line 7, in <module>
  File "zipimport", line 262, in load_module
  File "zipimport", line 259, in load_module
  File "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/tmpk4z91x3x/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 35, in <module>
  File "frozen plistlib", line 65, in <module>
ModuleNotFoundError: No module named 'xml.parsers'
```
