### ISSUE TITLE
Incompatibility for "__slots__" in customizing attribute access

### ISSUE THREAD

**Issue by Snowapril** [RustPython/RustPython#2842]
## Feature

If `__slots__` is defined in a class object, there must not be auto-generated `__dict__` attribute.
In default python, class object uses `__dict__` attributes to store object's instance attributes. 
But, with a `__slots__`, developer can tell the python not to use a `__dict__`.
But in RustPython, `__dict__` is still auto-generated even `__slots__` is defined.

#### In RustPython
```python
Welcome to the magnificent Rust Python 0.1.2 interpreter �  🖖
>>>>> class Test:
.....   __slots__ = "cost", "item"
.....   def __init__(self):
.....           self.cost = 10
.....           self.item = "icecream"
.....
>>>>> t = Test()
>>>>> t.__dict__
{'cost': 10, 'item': 'icecream'}
```

#### In CPython 3.8
```python
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Test:
...     __slots__ = "cost", "item"
...     def __init__(self):
...             self.cost = 10
...             self.item = "icecream"
...
>>> t = Test()
>>> t.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Test' object has no attribute '__dict__'
```

## Python Documentation

https://docs.python.org/3.8/reference/datamodel.html?highlight=__slots__#slots

**Comment by youknowone** [comment]
I have no idea we are correctly implementing `__slot__` for now. @coolreader18 do you have any idea?

**Comment by Snowapril** [comment]
I found there is no auto-generated __weakref__ in RustPython class object. In regardless of __slots__ is defined in object definition, RustPython's class object does not have __weakref__ attribute. But in CPython 3.8.5, there exists __weakref__ attribute if __slots__ is not defined in class definition.

#### RustPython
```python
Welcome to the magnificent Rust Python 0.1.2 interpreter �  🖖
>>>>> class A:
.....   __slots__ = "test"
.....   def __init__(self):
.....           self.test = 10
.....
>>>>> a = A()
>>>>> a.__weakref__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__weakref__'
>>>>> class B:
.....   def __init__(self):
.....           self.test = 10
.....
>>>>> b = B()
>>>>> b.__weakref__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'B' object has no attribute '__weakref__'
```

#### CPython 3.8
```python
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class A:
...     __slots__ = "test"
...     def __init__(self):
...             self.test = 10
...
>>> a = A()
>>> a.__weakref__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__weakref__'
>>> class B:
...     def __init__(self):
...             self.test = 10
...
>>> b = B()
>>> b.__weakref__
>>> 
```

**Comment by sobolevn** [comment]
Special case to keep in mind:

```python
Python 3.8.9 (default, May  3 2021, 12:15:25) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class A:
...   __slots__ = ('__dict__', 'a')
...   def __init__(self):
...     self.a = 1
...     self.b = 2
... 
>>> A().__dict__
{'b': 2}
```

**Comment by youknowone** [comment]
The main report is fixed 
```
>>>>> class Test:
.....   __slots__ = "cost", "item"
.....   def __init__(self):
.....           self.cost = 10
.....           self.item = "icecream"
..... 
>>>>> t = Test()
>>>>> t = Test()
>>>>> t.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Test' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by youknowone** [comment]
The special case is also fixed
```
>>>>> class A:
.....   __slots__ = ('__dict__', 'a')
.....   def __init__(self):
.....     self.a = 1
.....     self.b = 2
..... 
>>>>> A().__dict__
{'b': 2}
```

**Comment by youknowone** [comment]
The weakref is not fixed yet
