### ISSUE TITLE
Special types'  `__doc__` property should be readonly

### ISSUE THREAD

**Issue by moreal** [RustPython/RustPython#2916]
## Feature

Special types' `__doc__` property should be readonly (i.e. getter) except for user-defined type. But `__doc__` properties of RustPython's special types is writable.

### CPython

```
>>> SystemExit.__doc__
'Request to exit from the interpreter.'
>>> SystemExit.__doc__ = ""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't set attributes of built-in/extension type 'SystemExit'
>>> class A:
...   ...
... 
>>> A.__doc__ = "123"
>>> A.__doc__
'123'
```

### RustPython

```
>>>>> SystemExit.__doc__
'object()\n--\n\nThe base class of the class hierarchy.\n\nWhen called, it accepts no arguments and returns a new featureless\ninstance that has no instance attributes and cannot be given any.'
>>>>> SystemExit.__doc__ = ""
>>>>> class A:
.....   ...
..... 
>>>>> A.__doc__
>>>>> A.__doc__ = "123"
>>>>> A.__doc__
'123'
```
## Python Documentation

- [`type_getsets` definitions](https://github.com/python/cpython/blob/f5d7a8d29c49ad47254fa098abb7a510e5e7b45e/Objects/typeobject.c#L1035)
- [`type_set_doc(PyTypeObject *type, PyObject *value, void *context)`](https://github.com/python/cpython/blob/f5d7a8d29c49ad47254fa098abb7a510e5e7b45e/Objects/typeobject.c#L916-L923)
  - [check_set_special_type_attr(PyTypeObject *type, PyObject *value, const char *name)](https://github.com/python/cpython/blob/f5d7a8d29c49ad47254fa098abb7a510e5e7b45e/Objects/typeobject.c#L450-L472)

**Comment by muscar** [comment]
I can have a look at this.

**Comment by youknowone** [comment]
I didn't looked in this issue very well, but I guess `PyTypeFlags` would be related. If proper flag doesn't exist, one from CPython tp_flags would be needed to be added here too.

**Comment by Snowapril** [comment]
related:  https://github.com/RustPython/RustPython/pull/3821

`__doc__` is also obeying the `setattro` rule of the type. not specialized one.
If the type is `IMMUTABLE`, any attributes are non-writeable.
If the given type is not `IMMUTABLE`, we can also modify its `__doc__`
```python
>>> import contextlib
>>> contextlib.redirect_stderr.__doc__
'Context manager for temporarily redirecting stderr to another file.'
>>> contextlib.redirect_stderr.__doc__ = 10
>>> contextlib.redirect_stderr.__doc__
10
```

**Comment by youknowone** [comment]
#2766 looks similar

**Comment by youknowone** [comment]
```
>>>>> SystemExit.__doc__ = ""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot set '__doc__' attribute of immutable type 'SystemExit'
>>>>> 
```
