### ISSUE TITLE
Rust panicks when indenting in REPL

### ISSUE THREAD

**Issue by domdfcoding** [RustPython/RustPython#2925]
Attempting to insert a tab character before some text in the REPL results in a panic.

The sequence of keypresses is:

1. `a` (can be any character)
2. `Home` (or left arrow key)
3. `Tab`

Adding a space instead of a tab works fine.

I'm using the latest Rust version, and built RustPython from the latest commit.

-----

The backtrace is as follows:

<details>

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:147:28
stack backtrace:
   0:     0x55c702785070 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55c702785070 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c702785070 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c702785070 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c7027a926c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55c702780605 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55c70278727b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c70278727b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c70278727b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55c702786d51 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55c702787944 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55c7027873f7 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55c70278556c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55c702787389 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55c70138d501 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55c70138d44d - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55c7013b1587 - rustyline::complete_line::h03b496bbbeacf495
                               at /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:147:28
  17:     0x55c7013b2dc9 - rustyline::readline_edit::h2e02713c9bd96e20
                               at /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:485:24
  18:     0x55c7013afb39 - rustyline::readline_raw::hb8e015e905091d1f
                               at /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:574:22
  19:     0x55c7013b453a - rustyline::Editor<H>::readline_with::hd2e79fe9a628eabb
                               at /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:704:13
  20:     0x55c7013b471f - rustyline::Editor<H>::readline::h750fe965fce792db
                               at /home/domdf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-8.2.0/src/lib.rs:680:9
  21:     0x55c7013c8484 - rustpython_vm::readline::rustyline_readline::Readline<H>::readline::ha34975a11b7730bc
                               at /tmp/RustPython/vm/src/readline.rs:112:19
  22:     0x55c7013c09c1 - rustpython_vm::readline::Readline<H>::readline::hbb3001a387b4ed32
                               at /tmp/RustPython/vm/src/readline.rs:150:9
  23:     0x55c70139bb1f - rustpython::shell::run_shell::h64c4e2845f3b0748
                               at /tmp/RustPython/src/shell.rs:65:28
  24:     0x55c7013969b4 - rustpython::run_rustpython::ha0c5962b550ce9fa
                               at /tmp/RustPython/src/lib.rs:578:9
  25:     0x55c70138f263 - rustpython::run::{{closure}}::h676039dfe12940ac
                               at /tmp/RustPython/src/lib.rs:101:19
  26:     0x55c70138fcf9 - rustpython_vm::vm::Interpreter::enter::{{closure}}::h8cd76c4b16c73dbe
                               at /tmp/RustPython/vm/src/vm.rs:1977:39
  27:     0x55c70138fd90 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h72bfa643ea416a6a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  28:     0x55c70138dfbf - std::panicking::try::do_call::heacde1a2f320105b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  29:     0x55c70138e0cd - __rust_try
  30:     0x55c70138dede - std::panicking::try::hce1e7f3c687ae73e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  31:     0x55c70138fdcb - std::panic::catch_unwind::ha290216b47c8d042
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  32:     0x55c70138ea72 - rustpython_vm::vm::thread::enter_vm::{{closure}}::hef82cd8838718a1c
                               at /tmp/RustPython/vm/src/vm.rs:88:23
  33:     0x55c701390839 - std::thread::local::LocalKey<T>::try_with::ha927e097ab026600
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
  34:     0x55c7013906d2 - std::thread::local::LocalKey<T>::with::h3842b8f78430e505
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  35:     0x55c70138e877 - rustpython_vm::vm::thread::enter_vm::hb6f279cc6df6c09d
                               at /tmp/RustPython/vm/src/vm.rs:86:9
  36:     0x55c70138fcab - rustpython_vm::vm::Interpreter::enter::h6e5e1e8d277adf75
                               at /tmp/RustPython/vm/src/vm.rs:1977:9
  37:     0x55c70138f19b - rustpython::run::h4a7c6a744ae9ea96
                               at /tmp/RustPython/src/lib.rs:100:20
  38:     0x55c701390246 - rustpython::main::h4396087a4c0f8b4a
                               at /tmp/RustPython/src/main.rs:2:5
  39:     0x55c70138fe5b - core::ops::function::FnOnce::call_once::hb7973871f3acaaeb
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  40:     0x55c70138e0fe - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a16f278469beff0
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  41:     0x55c70138ed71 - std::rt::lang_start::{{closure}}::h3c768dafe4f1812e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
  42:     0x55c702787f49 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  43:     0x55c702787f49 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  44:     0x55c702787f49 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  45:     0x55c702787f49 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  46:     0x55c702787f49 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  47:     0x55c70138ed50 - std::rt::lang_start::h845e1d6ef923b173
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
  48:     0x55c70139026c - main
  49:     0x7f30f9b7b0b3 - __libc_start_main
  50:     0x55c70138dcfe - _start
  51:                0x0 - <unknown>

```

</details>

**Comment by DimitrisJim** [comment]
Thanks for the report! This should now be fixed.
