### ISSUE TITLE
The compatible problem for wasm32-wasi

### ISSUE THREAD

**Issue by gdjs2** [RustPython/RustPython#3052]
## Summary

I have just compiled the main branch of RustPython on macOS with wasi-sdk-12.0 and rustc 1.53.0. The compilation can be done correctly, while the standalone packet cannot be run on Wasmer and Wasmtime. :(

I have also tried with the same compiler on Ubuntu 20.04, which is the same result. So I guess that this may be some compatible problem for wasm.

### Wasmer 

```
thread 'main' panicked at 'initialization failed; run with RUST_BACKTRACE=1 to see Python backtrace', vm/src/vm.rs:811:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run `rustpython.wasm`
│   1: WASI execution failed
│   2: failed to run WASI `_start` function
│   3: RuntimeError: unreachable
           at __rust_start_panic (rustpython.wasm[11352]:0x892be8)
           at rust_panic (rustpython.wasm[11333]:0x891e16)
           at std::panicking::rust_panic_with_hook::h7d1c07b3a075203c (rustpython.wasm[11326]:0x8919ac)
           at std::panicking::begin_panic_handler::{{closure}}::h3513767ae6c4d95c (rustpython.wasm[11299]:0x890868)
           at std::sys_common::backtrace::__rust_end_short_backtrace::h0bbf8ae75ca302c2 (rustpython.wasm[11298]:0x8907a9)
           at rust_begin_unwind (rustpython.wasm[11325]:0x891850)
           at std::panicking::begin_panic_fmt::hd2af9882019c2342 (rustpython.wasm[11174]:0x888df9)
           at rustpython_vm::vm::VirtualMachine::_py_panic_failed::hfc1a4342369da6cf (rustpython.wasm[7399]:0x4d398d)
           at rustpython_vm::vm::VirtualMachine::expect_pyresult::{{closure}}::ha318545cd177fd97 (rustpython.wasm[7379]:0x4d0f7c)
           at rustpython_vm::vm::VirtualMachine::initialize::hf04ce04109d7f505 (rustpython.wasm[7374]:0x4cffa3)
           at rustpython_vm::vm::Interpreter::new_with_init::h521e31ffe3bf5662 (rustpython.wasm[61]:0x7469)
           at rustpython::run::he0c95f30cbac6d2a (rustpython.wasm[63]:0x75e7)
           at rustpython::main::h5516b9aa40484a29 (rustpython.wasm[46]:0x67ce)
           at std::sys_common::backtrace::__rust_begin_short_backtrace::he6946decdba5aa4f (rustpython.wasm[54]:0x6fa8)
           at std::rt::lang_start::{{closure}}::he42e4b05e8458974 (rustpython.wasm[49]:0x683e)
           at std::rt::lang_start_internal::h1e63ab493c96e529 (rustpython.wasm[11334]:0x891ec1)
           at __original_main (rustpython.wasm[47]:0x6805)
           at _start (rustpython.wasm[42]:0x6471)
           at _start.command_export (rustpython.wasm[11721]:0x8aed79)
╰─> 4: unreachable
```

### Wasmtime

```
thread 'main' panicked at 'initialization failed; run with RUST_BACKTRACE=1 to see Python backtrace', vm/src/vm.rs:811:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to run main module `rustpython.wasm`

Caused by:
    0: failed to invoke command default
    1: wasm trap: unreachable
       wasm backtrace:
           0: 0x892be8 - panic_abort::__rust_start_panic::abort::h8410222ecfb6d0a9
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/panic_abort/src/lib.rs:86:17
                     - __rust_start_panic
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/panic_abort/src/lib.rs:41:5
           1: 0x891e16 - rust_panic
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:640:9
           2: 0x8919ac - std::panicking::rust_panic_with_hook::h7d1c07b3a075203c
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:610:5
           3: 0x890868 - std::panicking::begin_panic_handler::{{closure}}::h3513767ae6c4d95c
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
           4: 0x8907a9 - std::sys_common::backtrace::__rust_end_short_backtrace::h0bbf8ae75ca302c2
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
           5: 0x891850 - rust_begin_unwind
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
           6: 0x888df9 - std::panicking::begin_panic_fmt::hd2af9882019c2342
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
           7: 0x4d398d - <unknown>!rustpython_vm::vm::VirtualMachine::_py_panic_failed::hfc1a4342369da6cf
           8: 0x4d0f7c - <unknown>!rustpython_vm::vm::VirtualMachine::expect_pyresult::{{closure}}::ha318545cd177fd97
           9: 0x4cffa3 - <unknown>!rustpython_vm::vm::VirtualMachine::initialize::hf04ce04109d7f505
          10: 0x7469 - <unknown>!rustpython_vm::vm::Interpreter::new_with_init::h521e31ffe3bf5662
          11: 0x75e7 - <unknown>!rustpython::run::he0c95f30cbac6d2a
          12: 0x67ce - <unknown>!rustpython::main::h5516b9aa40484a29
          13: 0x6fa8 - <unknown>!std::sys_common::backtrace::__rust_begin_short_backtrace::he6946decdba5aa4f
          14: 0x683e - <unknown>!std::rt::lang_start::{{closure}}::he42e4b05e8458974
          15: 0x891ec1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha4f60a9c9c7a97e0
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
                     - std::panicking::try::do_call::h30bf5b3340484c17
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
                     - std::panicking::try::h168ce69db8716de2
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
                     - std::panic::catch_unwind::h22e85b292aa7f362
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
                     - std::rt::lang_start_internal::h1e63ab493c96e529
                           at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
          16: 0x6805 - <unknown>!__original_main
          17: 0x6471 - <unknown>!_start
          18: 0x8aed79 - <unknown>!_start.command_export
```
Both runtime point to the same code.

**Comment by youknowone** [comment]
I believe this is fixed by adding `--features=frozen-stdlib` or `RUSTPYTHONPATH` on runtime. 

Try:
```sh 
$ cargo build --target wasm32-wasi --no-default-features --features freeze-stdlib,stdlib --release
$ RUST_BACKTRACE=1 wasmer run --dir . target/wasm32-wasi/release/rustpython.wasm extra_tests/snippets/stdlib_random.py     
```

**Comment by youknowone** [comment]
Please feel free to open issue again if you continuously experience the problem
