### ISSUE TITLE
Slow an crashing on windows 10 with wamp

### ISSUE THREAD

**Issue by trsh** [RustPython/RustPython#3441]
```
C:\Users\trsh\.wasmer\bin>wapm.exe run rustpython
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> 2+2

C:\Users\trsh\.wasmer\bin>
```

Windows 10 x64

**Comment by trsh** [comment]
And
```
C:\Projects\ML\ppp\RustPython>cargo run --release
    Finished release [optimized] target(s) in 0.37s
     Running `target\release\rustpython.exe`
Error in sys.excepthook:
lost sys.stderr
RuntimeError: lost sys.stderr
Original exception was:
lost sys.stderr
ModuleNotFoundError: No module named 'encodings'

The above exception was the direct cause of the following exception:

RuntimeError: Could not import encodings. Is your RUSTPYTHONPATH set? If you don't have access to a consistent external environment (e.g. if you're embedding rustpython in another application), try enabling the freeze-stdlib feature
thread 'main' panicked at 'initialization failed; exception backtrace above', vm\src\vm.rs:389:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
   2: rustpython_vm::vm::VirtualMachine::_py_panic_failed
   3: rustpython_vm::vm::VirtualMachine::initialize
   4: alloc::alloc::box_free
   5: <std::sync::poison::PoisonError<T> as core::fmt::Debug>::fmt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\rustpython.exe` (exit code: 101)
```

**Comment by youknowone** [comment]
did you try `cargo build --release` for build?

**Comment by trsh** [comment]
Necro answers =D. No I did not try anything

**Comment by youknowone** [comment]
I am sorry for the late reply. I recently tested wasi with wasmer and it didn't have problem.

Build
```
$ cargo build --target wasm32-wasi --no-default-features --features freeze-stdlib,stdlib --release
```

Run by wasmer
```
$ wasmer run --dir . target/wasm32-wasi/release/rustpython.wasm extra_tests/snippets/stdlib_random.py
```
