### ISSUE TITLE
Problems installing PIP on windows 10 x64

### ISSUE THREAD

**Issue by trsh** [RustPython/RustPython#3443]
```
C:\Projects\ML\ppp\RustPython\target\release>rustpython.exe --install-pip
downloading get-pip.py...
running get-pip.py...
Traceback (most recent call last):
  File "get-pip.py", line 27081, in <module>
  File "get-pip.py", line 143, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 139, in main
  File "get-pip.py", line 115, in bootstrap
  File "get-pip.py", line 96, in monkeypatch_for_cert
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\cli\base_command.py", line 13, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\cli\cmdoptions.py", line 23, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\cli\parser.py", line 12, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\configuration.py", line 20, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_internal\exceptions.py", line 7, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_vendor\pkg_resources\__init__.py", line 80, in <module>
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_vendor\platformdirs\__init__.py", line 31, in <module>
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_vendor\platformdirs\__init__.py", line 27, in _set_platform_dir_class
  File "C:\Projects\ML\ppp\RustPython\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 262, in load_module
    raise
  File "C:\Projects\ML\ppp\RustPython\Lib\zipimport.py", line 259, in load_module
    exec(code, mod.__dict__)
  File "C:\Users\trsh\AppData\Local\Temp\tmpgddclxyz\pip.zip\pip\_vendor\platformdirs\windows.py", line 1, in <module>
ModuleNotFoundError: No module named 'ctypes'
```

**Comment by Snowapril** [comment]
duplicate here #2671 😢
