### ISSUE TITLE
function __qualname__ is not getset

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4088]
## Feature

CPython
```
>>> def f(): pass
... 
>>> f.__qualname__
'f'
>>> del f.__qualname__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __qualname__ must be set to a string object
>>> 
```
See func_set_qualname

RustPython
```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> def f(): pass
>>>>> 
>>>>> f.__qualname__
'f'
>>>>> f.__qualname__ = 'x'
>>>>> f.__qualname__
'x'
>>>>> del f.__qualname__
>>>>> f.__qualname__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute '__qualname__'
```

**Comment by youknowone** [comment]
generator(PyGenerator), coroutine, and asyncgenerator also have similar issues.

**Comment by oow214** [comment]
@youknowone Could you assign me to this issue?
