### ISSUE TITLE
Install pip failed

### ISSUE THREAD

**Issue by baitian752** [RustPython/RustPython#4332]
```text
$ rustpython --install-pip
Traceback (most recent call last):
  File "runpy", line 197, in _run_module_as_main
  File "runpy", line 86, in _run_code
  File "ensurepip.__main__", line 5, in <module>
  File "ensurepip", line 283, in _main
  File "ensurepip", line 160, in _bootstrap
  File "ensurepip", line 169, in _bootstrap
  File "importlib.resources", line 88, in read_binary
  File "importlib.resources", line 1, in open_binary
FileNotFoundError: 'setuptools-58.1.0-py3-none-any.whl' resource not found in 'ensurepip._bundled'
```

Revision: c48c2290f44eabcae85fd6d056776f53cea10a30
Build target: x86_64-unknown-linux-musl
Build type: release
Features: ssl,freeze-stdlib

**Comment by ishaan-jaff** [comment]
What version of Python are you running? - [https://clerkie.co/](Clerkie)

**Comment by Alfex4936** [comment]
same here for ssl,jit,freeze-stdlib

**Comment by DimitrisJim** [comment]
Hm, not sure how this plays with freezing. You can get pip with `--install-pip get-pip` for now though, since that grabs it from bootstrap.pypa.io.

**Comment by youknowone** [comment]
Maybe we missed to bundle *.whl during freezing

**Comment by youknowone** [comment]
oh, yep. freezing is bundling compiled bytecode. binaries which is not directly compiled into bytecode are not frozen.
