### ISSUE TITLE
`eval` doesn't raise correct exception

### ISSUE THREAD

**Issue by yt2b** [RustPython/RustPython#4375]
```py
class X:
    def __getitem__(self, key):
        raise ValueError

eval("foo", {}, X())
```

On CPython, The output of this code is below.

```
Traceback (most recent call last):
  File "/Users/yusuke/Programs/Rust/Github/RustPython/imp.py", line 9, in <module>
    eval("foo", {}, X())
  File "<string>", line 1, in <module>
  File "/Users/yusuke/Programs/Rust/Github/RustPython/imp.py", line 6, in __getitem__
    raise ValueError
ValueError
```

But on RustPython, The output is different.

```
Traceback (most recent call last):
  File "imp.py", line 9, in <module>
    eval("foo", {}, X())
  File "<string>", line 1, in <module>
NameError: name 'foo' is not defined
```

I'll look into this.

**Comment by yt2b** [comment]
This bug occures from `LoadNameAny` opecode.

https://github.com/RustPython/RustPython/blob/b1db1be031cfa69604d05dde187932ab94edb503/vm/src/frame.rs#L539-L547

`self.locals.mapping().subscript(name, vm)` returns value of the name.
If the name is not found in locals, it returns `KeyError`.
But because of calling `ok` function, returned exceptions is ignored.

If the name is not found in local, `self.load_global_or_builtin(name, vm)` is called.
This function returns value of the name.
If the name is not found in global, it returns `NameError`.

Returned exception from local is ignored, So `NameError` always occures if name is not found.
