### ISSUE TITLE
Segmentation fault in handling multiple free in sqlite3

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4728]
In pysqlite, set_isolation_level may result in memory getting freed multiple times and hence lead to segfault. See the following example.

test.py
```
import sqlite3

class S(str):

    def __del__(self):
        self.isolation_level = S('B')
conn = sqlite3.connect('poc6.db')
conn.isolation_level = S('A')
conn.isolation_level = ''
```

Crash message:
Segmentation Fault

Reproduce step:
install rustpython with command "cargo install --git https://github.com/RustPython/RustPython", then "rustpython test.py"

Environment:
Ubuntu 18.04
rustic 1.68.0
rustpython v0.2.0 (#a824e7b3)

**Comment by fanninpm** [comment]
Does this also happen in CPython?

**Comment by xiaxinmeng** [comment]
Thanks, it does not produce a crash in CPython, but constantly prints the exception.

Behavior on CPython (3.12.0a6+ commit0708437):
```
Exception ignored in: <function S.__del__ at 0x7f2d41b420c0>
Traceback (most recent call last):
  File "/home/xxm/Desktop/test.py", line 16, in __del__
    conn.isolation_level = S('B')
    ^^^^^^^^^^^^^^^^^^^^
ValueError: isolation_level string must be '', 'DEFERRED', 'IMMEDIATE', or 'EXCLUSIVE'
Exception ignored in: <function S.__del__ at 0x7f2d41b420c0>
Traceback (most recent call last):
  File "/home/xxm/Desktop/test.py", line 16, in __del__
    conn.isolation_level = S('B')
    ^^^^^^^^^^^^^^^^^^^^
ValueError: isolation_level string must be '', 'DEFERRED', 'IMMEDIATE', or 'EXCLUSIVE'
.......
```
