### ISSUE TITLE
IPython  support

### ISSUE THREAD

**Issue by amorenoz** [RustPython/RustPython#4791]
## Feature

Support for running IPython both as module `rustpython -m IPython` and as part of a script `rustpython -c "import IPython; IPython.embed()"` 

Currently, it fails:

```
> cargo install --git https://github.com/RustPython/RustPython --branch main  --features=ssl && rustpython --install-pip get-pip && rustpython -m pip install IPython && rustpython -c "import IPython"
[...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/IPython/__init__.py", line 52, in <module>
    from .core.application import Application
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core import release, crashhandler
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/IPython/core/ultratb.py", line 101, in <module>
    import stack_data
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/stack_data/__init__.py", line 1, in <module>
    from .core import Source, FrameInfo, markers_from_ranges, Options, LINE_GAP, Line, Variable, RangeInLine, \
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/stack_data/core.py", line 15, in <module>
    import executing
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/executing/__init__.py", line 12, in <module>
    from .executing import Source, Executing, only, NotOneValueFound, cache, future_flags
  File "/home/amorenoz/.local/lib/rustpython3.11/site-packages/executing/executing.py", line 95, in <module>
    _get_instructions = dis.get_instructions
AttributeError: module 'dis' has no attribute 'get_instructions'

```

## Python Documentation
https://ipython.readthedocs.io/en/stable/index.html

**Comment by DimitrisJim** [comment]
Yup. This would be dope. I'm pretty sure this would lead to a couple of issues being discovered (currently fails on `get_instructions` not being there apparently).

**Comment by DimitrisJim** [comment]
Shouldn't be difficult, don't remember file at the top of my head but if you grep for other AST constants you'll probably find the file.

**Comment by fanninpm** [comment]
Is it [`vm/src/stdlib/ast.rs`](https://github.com/RustPython/RustPython/blob/main/vm/src/stdlib/ast.rs)?

**Comment by itsankitkp** [comment]
Opened WIP PR, lots of stuffs need to be done for this but it is interesting project.
