### ISSUE TITLE
Panicked if the decorator takes a generator as arguments

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4855]
The following code defines a class named Foo using the jitclass decorator from the numba.experimental module. The jitclass decorator is passed a for-in loop. RustPython crashes.

test.py 
```
from numba.experimental import jitclass
@jitclass({1 for x in range(0,1)})
class Foo():
    pass
```

crash message:
```
thread 'main' panicked at 'The symbol must be present in the symbol table, even when it is undefined in python.', compiler/codegen/src/compile.rs:478:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Environment:
Ubuntu 18.04
rustpython v0.2.0

**Comment by fanninpm** [comment]
What happens in CPython?

**Comment by xiaxinmeng** [comment]
Behavior on CPython 3.10.8
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/IFuzzer/experiment_on_different_interpreter/rustpython/test.py", line 219, in <module>
    class Foo():
  File "/home/xxm/.local/lib/python3.10/site-packages/numba/experimental/jitclass/decorators.py", line 77, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "/home/xxm/.local/lib/python3.10/site-packages/numba/experimental/jitclass/base.py", line 182, in register_class_type
    _validate_spec(spec)
  File "/home/xxm/.local/lib/python3.10/site-packages/numba/experimental/jitclass/base.py", line 131, in _validate_spec
    for k, v in spec.items():
AttributeError: 'set' object has no attribute 'items'
```

**Comment by DimitrisJim** [comment]
Nice, thanks! Another instance of #4848, closing as duplicate.
