### ISSUE TITLE
distutils.sysconfig.customize_compiler() produces TypeError

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4984]
## Summary
In Python, distutils.ccompiler provides an interface for compiling and linking C/C++ code. 

```
import distutils.ccompiler

c = distutils.ccompiler.new_compiler()
print(c.compiler)

distutils.sysconfig.customize_compiler(c)
print(c.compiler)
```

## Expected

Output on CPython3.9: 
```
['cc']
['gcc', '-pthread', '-Wno-unused-result', '-Wsign-compare', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall']
```

## Actual

RustPython reports a TypeError:
```
['cc']
<distutils.unixccompiler.UnixCCompiler object at 0x55f4f18fb7c0>
Traceback (most recent call last):
  File "/home/xxm/Desktop/RustPython/example.py", line 197, in <module>
    distutils.sysconfig.customize_compiler(c)
  File "/home/xxm/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/59df92d/pylib/Lib/distutils/sysconfig.py", line 217, in customize_compiler
    cpp = cc + " -E"           # not always
TypeError: '+' not supported between instances of 'NoneType' and 'str'
```

## Environment

RustPython: v0.2.0 (https://github.com/RustPython/RustPython#59df92d7)
CPython: 3.9.0
Ubuntu 18.04

**Comment by DimitrisJim** [comment]
First stab at this would be updating distutils to the most recent Python version. Reference https://github.com/RustPython/RustPython/issues/4564

**Comment by youknowone** [comment]
distutils is removed in Python 3.12
