### ISSUE TITLE
lexer panic

### ISSUE THREAD

**Issue by janczer** [RustPython/RustPython#501]
Here the panic in lexer:

```
>>>>> \0
thread 'main' panicked at 'Not impl Some('\\')', parser/src/lexer.rs:1036:21
>>>>> `
thread 'main' panicked at 'Not impl Some('`')', parser/src/lexer.rs:1036:21
```

Python:
```
>>> `
  File "<stdin>", line 1
    `
    ^
SyntaxError: invalid syntax
>>> \0
  File "<stdin>", line 1
    \0
     ^
SyntaxError: unexpected character after line continuation character
```

**Comment by AaronRocinante** [comment]
Please take a look at PR #552

**Comment by windelbouwman** [comment]
The panic is resolved. Error reporting can be improved, but I would say, that is a different issue.
