### ISSUE TITLE
 Request for pythonnet full support. 

### ISSUE THREAD

**Issue by ANVLISTENER** [RustPython/RustPython#5032]
PS C:\Users\712645\Desktop> rspy -c "import clr_loader; from clr_loader import get_coreclr; runtime = get_coreclr()"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\712645\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\clr_loader\__init__.py", line 117, in get_coreclr
    from .hostfxr import DotnetCoreRuntime
  File "C:\Users\712645\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\clr_loader\hostfxr.py", line 5, in <module>
    from .ffi import ffi, load_hostfxr
  File "C:\Users\712645\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\clr_loader\ffi\__init__.py", line 11, in <module>
    ffi = cffi.FFI()  # type: ignore
  File "C:\Users\712645\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\cffi\api.py", line 48, in __init__
    import _cffi_backend as backend
ModuleNotFoundError: No module named '_cffi_backend'
PS C:\Users\712645\Desktop> rspy -c "import ctypes"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\712645\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
PS C:\Users\712645\Desktop> rspy -c "import _ctypes"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_ctypes'
PS C:\Users\712645\Desktop> rspy -c "import _ctypes"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_ctypes'

**Comment by fanninpm** [comment]
It seems this would require a Rust implementation of the `_ctypes` module, which seems to be a difficult problem to solve. (See also #1217.) If you are up for the challenge, would you like to help?

**Comment by ANVLISTENER** [comment]
Hi Team ,

I am up for the challenge.

Let me know how to contribute for the challenge to solve.

I will try to write it in my github if not started.

Nice to see you!.

Thank you.

Regards ,
Libin
