### ISSUE TITLE
Request for the pandas package support. 

### ISSUE THREAD

**Issue by ANVLISTENER** [RustPython/RustPython#5033]
PS C:\Users\username\Desktop> rspy -c "import pandas"
_frozen_importlib:241: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\bdb0c8f\Lib\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(_missing_dependencies)
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\username\.cargo\bin\rspy.exe"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by arihant2math** [comment]
Duplicate of #158
