### ISSUE TITLE
error in the logic in python os module output. 

### ISSUE THREAD

**Issue by ANVLISTENER** [RustPython/RustPython#5038]
C:\Users\username\Desktop>rspy ./hello.py
.

C:\Users\username\Desktop>python ./hello.py
C:\Users\username\Desktop

C:\Users\username\Desktop>rspy C:\Users\username\Desktop/hello.py
[ERROR rustpython_vm::vm::compile] Failed reading file 'C:\Users\username\OneDrive': The system cannot find the file specified. (os error 2)

C:\Users\username\Desktop>

C:\Users\username\Desktop>rspy "C:\Users\username\Desktop\hello.py"
C:\Users\username\Desktop

C:\Users\username\Desktop>

**Comment by ANVLISTENER** [comment]
hello.py: 

import os 

print(os.path.dirname(__file__))

**Comment by hwoithe** [comment]
What version of Python were you testing this with?

Depending on your version of Python, the `__file__` attribute may be an absolute path or a relative path.

```
$ cat 5038.py
print(__file__)

$ docker run --network host -it --rm -v $(pwd)/5038.py:/tmp/5038.py python:3.8-slim /bin/bash -c "cd /tmp; python3 5038.py"
5038.py

$ docker run --network host -it --rm -v $(pwd)/5038.py:/tmp/5038.py python:3.9-slim /bin/bash -c "cd /tmp; python3 5038.py"
/tmp/5038.py

$ docker run --network host -it --rm -v $(pwd)/5038.py:/tmp/5038.py python:3.10-slim /bin/bash -c "cd /tmp; python3 5038.py"
/tmp/5038.py

$ docker run --network host -it --rm -v $(pwd)/5038.py:/tmp/5038.py python:3.11-slim /bin/bash -c "cd /tmp; python3 5038.py"
/tmp/5038.py
```

The behavior changed in Python 3.9 as documented [here](https://docs.python.org/3.9/whatsnew/3.9.html#other-language-changes).

```
$ rustpython --version
RustPython 0.3.0

$ cp 5038.py /tmp/5038.py
$ cd /tmp
$ rustpython 5038.py
5038.py
```

It appears that the current RustPython version matches the Python 3.8 behavior.

A possible solution is to modify [`run_script`](https://github.com/RustPython/RustPython/blob/21cff29c31c127b69eb5b8899452c09f4ede4a56/vm/src/vm/compile.rs#L29) to call [`run_code_string`](https://github.com/RustPython/RustPython/blob/21cff29c31c127b69eb5b8899452c09f4ede4a56/vm/src/vm/compile.rs#L47) with an [absolute path](https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.canonicalize).

```
$ rustpython 5038.py
/tmp/5038.py
```

This would also cause the traceback to contain the absolute path.

Before:
```
$ pwd
/tmp
$ cat 5038-traceback.py
raise Exception("5038")

$ rustpython 5038-traceback.py
Traceback (most recent call last):
  File "5038-traceback.py", line 1, in <module>
    raise Exception("5038")
Exception: 5038
```

After:
```
$ rustpython 5038-traceback.py
Traceback (most recent call last):
  File "/tmp/5038-traceback.py", line 1, in <module>
    raise Exception("5038")
Exception: 5038

$ python3 --version
Python 3.10.12
$ python3 5038-traceback.py
Traceback (most recent call last):
  File "/tmp/5038-traceback.py", line 1, in <module>
    raise Exception("5038")
Exception: 5038
```

I'm sure this solution will require more thought and testings.

**Comment by ANVLISTENER** [comment]
hi hwoithe, 

The python version is python 3.11 and the rustpython is RustPython 0.2.0. 

Kindly help, 

     Thank you.  

Regards , 

ANVLISTENER
