### ISSUE TITLE
await not allowed in comprehension in async def

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#5315]
## Feature

code
```python
async def f():
    [await a for a in range(1)]
```

expected: No error

Actual:
```sh
  File "z.py", line 2
    [await a for a in range(1)]
     ^
SyntaxError: 'await' outside async function
```

**Comment by hydrogen602** [comment]
Sidenote: It looks like the test `extra_tests/snippets/syntax_async.py` is broken (before my changes). However, I did see it run correctly once, but I haven't been able to reproduce that one run. 

It outputs:
```
Entrada
val = 1
Wiedersehen
Entrada
val = 1
Wiedersehen
Entrada
val = 1
Wiedersehen
Entrada
val = 1
Wiedersehen
Traceback (most recent call last):
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/extra_tests/snippets/syntax_async.py", line 89, in <module>
    raise
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/extra_tests/snippets/syntax_async.py", line 85, in <module>
    test()
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/extra_tests/snippets/syntax_async.py", line 79, in test
    asyncio.run(run(), debug=True)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/runners.py", line 129, in run
    signal.signal(signal.SIGINT, signal.default_int_handler)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/runners.py", line 124, in run
    raise  # CancelledError
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/extra_tests/snippets/syntax_async.py", line 52, in run
    await asyncio.wait(tasks)
  File "/Users/Jonathan/Documents/GitHub/OpenSource/RustPython/pylib/Lib/asyncio/tasks.py", line 460, in wait
    if any(coroutines.iscoroutine(f) for f in fs):
TypeError: object async_generator can't be used in 'await' expression
```
