### ISSUE TITLE
Implement _ (underscore) in the REPL

### ISSUE THREAD

**Issue by Jongy** [RustPython/RustPython#908]
In CPython:

```
>>> 1
1
>>> _
1
>>> 
```

In RustPython:

```
>>>>> 1
1
>>>>> _
Traceback (most recent call last):
  File "<stdin>", line 0, in <module>
NameError: name '_' is not defined
>>>>> 
```

**Comment by coolreader18** [comment]
This is pretty interesting, here's some other things to take into account if anyone wants to implement this:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> _
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_' is not defined
>>> 9
9
>>> _
9
>>> _; 8; _
9
8
8
```

**Comment by sapir** [comment]
I'm trying this now

**Comment by Jongy** [comment]
Solved (at least partially, as per https://github.com/RustPython/RustPython/issues/921) in https://github.com/RustPython/RustPython/pull/912,
