### ISSUE TITLE
Module import is not retried if re-imported after an error

### ISSUE THREAD

**Issue by Jongy** [RustPython/RustPython#950]
```
$ cat Lib/foo.py
bar
```

In CPython (3.7.0):
```
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Lib\foo.py", line 1, in <module>
    bar
NameError: name 'bar' is not defined
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Lib\foo.py", line 1, in <module>
    bar
NameError: name 'bar' is not defined
```

Importing the file for the 2nd time executes the file again, since the first execution resulted in an error.

In RustPython:
```
>>>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Lib\foo.py", line 1, in <module>
NameError: name 'bar' is not defined
>>>>> import foo
>>>>> foo
<module object at 0x1b55fd39f70>
>>>>>
```

Module import apparently succeeded although an exception was encountered.

Actually, the more severe error here is that after the second import, the module is registered and a module object is created regardless of whether the import should have executed successfully or not.

**Comment by youknowone** [comment]
fixed but untracked
